In [1]:
import pandas as pd
import numpy as np

In [2]:
df12 = pd.read_csv('../../../scraping/men/olympics/olympic2012men_final/Gymnastics_ 2012_Olympics_Men\'s_artistic_pommel_horse.csv')
df16 = pd.read_csv('../../../scraping/men/olympics/olympic2016men/Gymnastics_ 2016_Olympics_Men\'s_artistic_pommel_horse.csv')
df20 = pd.read_csv('../../../scraping/men/olympics/mens202olympics_fianl/Gymnastics_ 2020_Olympics_Men\'s_artistic_pommel_horse.csv')

In [4]:
df12.head(1)

   Rank          Gymnast   Nation  D Score  E Score  Pen.    Total
0     1  Krisztián Berki  Hungary      6.9    9.166   NaN  16.066*

In [5]:
df16.head(1)

   Rank       Gymnast         Nation  D Score  E Score  Pen.   Total
0     1  Max Whitlock  Great Britain      7.2    8.766   NaN  15.966

In [6]:
df20.head(1)

   Rank            Gymnast  D Score  E Score  Pen.   Total
0     1  Max Whitlock(GBR)      7.0    8.583   NaN  15.583

In [7]:
df20['year'] = 2020
df16['year'] = 2016
df12['year'] = 2012

In [8]:
df20['Nation'] = df20['Gymnast'].str.extract(r'\((.*?)\)')
df20['Gymnast'] = df20['Gymnast'].str.replace(r'\([^)]*\)', '', regex=True)

In [9]:
combined_df = pd.concat([df12, df16, df20], axis=0)

# Reset the index if needed
combined_df.reset_index(drop=True, inplace=True)

In [10]:
df= combined_df.copy()

In [11]:
df = df.fillna(0)

In [12]:
df

,Rank,Gymnast,Nation,D Score,E Score,Pen.,Total,year
0,1,Krisztián Berki,Hungary,6.9,9.166,0.0,16.066*,2012
1,2,Louis Smith,Great Britain,7.0,9.066,0.0,16.066*,2012
2,3,Max Whitlock,Great Britain,6.6,9.000,0.0,15.6,2012
3,4,Alberto Busnari,Italy,6.6,8.800,0.0,15.4,2012
4,5,Cyril Tommasone,France,6.5,8.641,0.0,15.141,2012
5,6,Vitaliy Nakonechnyi,Ukraine,6.3,8.466,0.0,14.766,2012
6,7,David Belyavskiy,Russia,6.3,8.433,0.0,14.733,2012
7,8,Vid Hidvégi,Hungary,6.3,8.000,0.0,14.3,2012
8,1,Max Whitlock,Great Britain,7.2,8.766,0.0,15.966,2016
9,2,Louis Smith,Great Britain,6.9,8.933,0.0,15.833,2016
10,3,Alexander Naddour,United States,6.8,8.900,0.0,15.7,2016
11,4,Cyril Tommasone,France,6.9,8.700,0.0,15.6,2016
12,5,David Belyavskiy,Russia,6.6,8.800,0.0,15.4,2016
13,6,Nikolai Kuksenkov,Russia,6.8,8.433,0.0,15.233,2016
14,7,Harutyun Merdinyan,Armenia,6.4,8.533,0.0,14.933,2016
15,8,Oleg Verniaiev,Ukraine,5.7,6.700,0.0,12.4,2016
16,1,Max Whitlock,GBR,7.0,8.583,0.0,15.583,2020
17,2,Lee Chih-kai,TPE,6.7,8.700,0.0,15.4,2020
18,3,Kazuma Kaya,JPN,6.6,8.300,0.0,14.9,2020
19,4,David Belyavskiy,ROC,6.4,8.433,0.0,14.833,2020
20,5,Kohei Kameyama,JPN,6.8,7.800,0.0,14.6,2020
21,6,Alec Yoder,USA,6.4,8.166,0.0,14.566,2020
22,7,Rhys McClenaghan,IRL,6.4,6.700,0.0,13.1,2020
23,8,Sun Wei,CHN,6.3,6.766,0.0,13.066,2020

In [13]:
df["Nation"].value_counts()

Nation
Great Britain    4
Russia           3
Hungary          2
France           2
Ukraine          2
JPN              2
Italy            1
United States    1
Armenia          1
GBR              1
TPE              1
ROC              1
USA              1
IRL              1
CHN              1
Name: count, dtype: int64

In [14]:
# Use the replace method to change values
df['Nation'] = df['Nation'].replace({'China': 'CHN', 'Japan': 'JPN',
                                    'Russia': 'RUS', 'Romania': 'RUM',
                                    'Germany': 'GER', 'Cuba': 'CUB',
                                    'United States': 'USA', 'Ukraine': 'UKR',
                                    'Greece': 'GRE', 'Mexico': 'MEX',
                                    'France': 'FRA', 'Netherlands': 'NED',
                                    'Brazil': 'BRA', "Great Britain": 'GBR',
                                    'South Korea': 'KOR', 'Hungary': 'HUN',
                                    'Armenia': 'ARM'})

In [15]:
df

    Rank              Gymnast Nation  D Score  E Score  Pen.    Total  year
0      1      Krisztián Berki    HUN      6.9    9.166   0.0  16.066*  2012
1      2          Louis Smith    GBR      7.0    9.066   0.0  16.066*  2012
2      3         Max Whitlock    GBR      6.6    9.000   0.0     15.6  2012
3      4      Alberto Busnari  Italy      6.6    8.800   0.0     15.4  2012
4      5      Cyril Tommasone    FRA      6.5    8.641   0.0   15.141  2012
5      6  Vitaliy Nakonechnyi    UKR      6.3    8.466   0.0   14.766  2012
6      7     David Belyavskiy    RUS      6.3    8.433   0.0   14.733  2012
7      8          Vid Hidvégi    HUN      6.3    8.000   0.0     14.3  2012
8      1         Max Whitlock    GBR      7.2    8.766   0.0   15.966  2016
9      2          Louis Smith    GBR      6.9    8.933   0.0   15.833  2016
10     3    Alexander Naddour    USA      6.8    8.900   0.0     15.7  2016
11     4      Cyril Tommasone    FRA      6.9    8.700   0.0     15.6  2016
12     5     David Belyavskiy    RUS      6.6    8.800   0.0     15.4  2016
13     6    Nikolai Kuksenkov    RUS      6.8    8.433   0.0   15.233  2016
14     7   Harutyun Merdinyan    ARM      6.4    8.533   0.0   14.933  2016
15     8       Oleg Verniaiev    UKR      5.7    6.700   0.0     12.4  2016
16     1         Max Whitlock    GBR      7.0    8.583   0.0   15.583  2020
17     2         Lee Chih-kai    TPE      6.7    8.700   0.0     15.4  2020
18     3          Kazuma Kaya    JPN      6.6    8.300   0.0     14.9  2020
19     4     David Belyavskiy    ROC      6.4    8.433   0.0   14.833  2020
20     5       Kohei Kameyama    JPN      6.8    7.800   0.0     14.6  2020
21     6           Alec Yoder    USA      6.4    8.166   0.0   14.566  2020
22     7     Rhys McClenaghan    IRL      6.4    6.700   0.0     13.1  2020
23     8              Sun Wei    CHN      6.3    6.766   0.0   13.066  2020

In [33]:
dff = df.copy()

In [34]:
dff

    Rank              Gymnast Nation  D Score  E Score  Pen.    Total  year
0      1      Krisztián Berki    HUN      6.9    9.166   0.0  16.066*  2012
1      2          Louis Smith    GBR      7.0    9.066   0.0  16.066*  2012
2      3         Max Whitlock    GBR      6.6    9.000   0.0     15.6  2012
3      4      Alberto Busnari  Italy      6.6    8.800   0.0     15.4  2012
4      5      Cyril Tommasone    FRA      6.5    8.641   0.0   15.141  2012
5      6  Vitaliy Nakonechnyi    UKR      6.3    8.466   0.0   14.766  2012
6      7     David Belyavskiy    RUS      6.3    8.433   0.0   14.733  2012
7      8          Vid Hidvégi    HUN      6.3    8.000   0.0     14.3  2012
8      1         Max Whitlock    GBR      7.2    8.766   0.0   15.966  2016
9      2          Louis Smith    GBR      6.9    8.933   0.0   15.833  2016
10     3    Alexander Naddour    USA      6.8    8.900   0.0     15.7  2016
11     4      Cyril Tommasone    FRA      6.9    8.700   0.0     15.6  2016
12     5     David Belyavskiy    RUS      6.6    8.800   0.0     15.4  2016
13     6    Nikolai Kuksenkov    RUS      6.8    8.433   0.0   15.233  2016
14     7   Harutyun Merdinyan    ARM      6.4    8.533   0.0   14.933  2016
15     8       Oleg Verniaiev    UKR      5.7    6.700   0.0     12.4  2016
16     1         Max Whitlock    GBR      7.0    8.583   0.0   15.583  2020
17     2         Lee Chih-kai    TPE      6.7    8.700   0.0     15.4  2020
18     3          Kazuma Kaya    JPN      6.6    8.300   0.0     14.9  2020
19     4     David Belyavskiy    ROC      6.4    8.433   0.0   14.833  2020
20     5       Kohei Kameyama    JPN      6.8    7.800   0.0     14.6  2020
21     6           Alec Yoder    USA      6.4    8.166   0.0   14.566  2020
22     7     Rhys McClenaghan    IRL      6.4    6.700   0.0     13.1  2020
23     8              Sun Wei    CHN      6.3    6.766   0.0   13.066  2020

In [36]:
dff['Total'] = dff['Total'].astype(str).apply(lambda x: x.replace('*', ''))

In [37]:
dff

    Rank              Gymnast Nation  D Score  E Score  Pen.   Total  year
0      1      Krisztián Berki    HUN      6.9    9.166   0.0  16.066  2012
1      2          Louis Smith    GBR      7.0    9.066   0.0  16.066  2012
2      3         Max Whitlock    GBR      6.6    9.000   0.0    15.6  2012
3      4      Alberto Busnari  Italy      6.6    8.800   0.0    15.4  2012
4      5      Cyril Tommasone    FRA      6.5    8.641   0.0  15.141  2012
5      6  Vitaliy Nakonechnyi    UKR      6.3    8.466   0.0  14.766  2012
6      7     David Belyavskiy    RUS      6.3    8.433   0.0  14.733  2012
7      8          Vid Hidvégi    HUN      6.3    8.000   0.0    14.3  2012
8      1         Max Whitlock    GBR      7.2    8.766   0.0  15.966  2016
9      2          Louis Smith    GBR      6.9    8.933   0.0  15.833  2016
10     3    Alexander Naddour    USA      6.8    8.900   0.0    15.7  2016
11     4      Cyril Tommasone    FRA      6.9    8.700   0.0    15.6  2016
12     5     David Belyavskiy    RUS      6.6    8.800   0.0    15.4  2016
13     6    Nikolai Kuksenkov    RUS      6.8    8.433   0.0  15.233  2016
14     7   Harutyun Merdinyan    ARM      6.4    8.533   0.0  14.933  2016
15     8       Oleg Verniaiev    UKR      5.7    6.700   0.0    12.4  2016
16     1         Max Whitlock    GBR      7.0    8.583   0.0  15.583  2020
17     2         Lee Chih-kai    TPE      6.7    8.700   0.0    15.4  2020
18     3          Kazuma Kaya    JPN      6.6    8.300   0.0    14.9  2020
19     4     David Belyavskiy    ROC      6.4    8.433   0.0  14.833  2020
20     5       Kohei Kameyama    JPN      6.8    7.800   0.0    14.6  2020
21     6           Alec Yoder    USA      6.4    8.166   0.0  14.566  2020
22     7     Rhys McClenaghan    IRL      6.4    6.700   0.0    13.1  2020
23     8              Sun Wei    CHN      6.3    6.766   0.0  13.066  2020

In [38]:
# df.to_csv('cleaned_mens2012to2020ph', index=False)