In [1]:
import pandas as pd 
import numpy as np

In [2]:
bb = pd.read_csv('../../../scraping/women/worldcup13cott/worldcup2013cott_bb.csv')

In [3]:
bbq = pd.read_csv('../../../scraping/women/worldcup13cott/worldcup2013cott_bb_qual.csv')

In [4]:
bb['round'] = 'final'

In [5]:
bbq['round'] = 'qual'

In [6]:
combined_df = pd.concat([bb, bbq])

In [7]:
combined_df

,Rank,Athlete,Nation,D,E,ND,Total,round
0,1,Anastasia Grishina,Russia,5.8,8.800,NaN,14.600,final
1,2,Vasiliki Millousi,Greece,5.7,8.600,NaN,14.300,final
2,3,Anna Dementyeva,Russia,6.0,8.275,-0.1,14.175,final
3,4,Noel van Klaveren,Netherlands,5.1,8.425,NaN,13.525,final
4,5,Maria Paula Vargas,Spain,5.8,7.525,NaN,13.325,final
5,6,Filipa Martins,Portugal,4.9,8.175,NaN,13.075,final
6,7,Oksana Chusovitina,Uzbekistan,5.5,7.650,-0.1,13.050,final
7,8,Dilnoza Abdusalimova,Uzbekistan,5.1,7.850,-0.1,12.850,final
0,1,Anastasia Grishina,Russia,5.6,8.450,NaN,14.050,qual
1,2,Noel van Klaveren,Netherlands,5.4,8.450,NaN,13.850,qual
2,3,Vasiliki Millousi,Greece,5.3,8.500,NaN,13.800,qual
3,4,Oksana Chusovitina,Uzbekistan,5.4,8.250,NaN,13.650,qual
4,5,Anna Dementyeva,Russia,6.1,7.550,NaN,13.650,qual
5,6,Maria Paula Vargas,Spain,5.8,7.800,NaN,13.600,qual
6,7,Filipa Martins,Portugal,5.3,8.500,-0.5,13.300,qual
7,8,Dilnoza Abdusalimova,Uzbekistan,5.1,8.050,-0.1,13.050,qual
8,9,Kristyna Palesova,Czech Republic,5.3,7.700,NaN,13.000,qual
9,10,Huang Huidan,China,5.7,7.400,-0.1,13.000,qual
10,11,Maija Leinonen,Finland,4.9,8.000,NaN,12.900,qual
11,12,Hiu Ying Angel Wong,Hong Kong,4.6,8.200,NaN,12.800,qual
12,13,Elisa HÃ¤mmerle,Austria,5.2,7.700,-0.1,12.800,qual
13,14,Jessica Lopez,Venezuela,5.7,6.950,NaN,12.650,qual
14,15,Silvia Colussi Pelaez,Spain,5.8,6.650,NaN,12.450,qual
15,16,Chantysha Netteb,Netherlands,5.0,7.350,NaN,12.350,qual
16,17,Ida Gustafsson,Sweden,5.3,6.900,NaN,12.200,qual
17,18,Cagla Akyol,Germany,5.5,6.550,NaN,12.050,qual
18,19,Pauline SchÃ¤fer,Germany,4.6,7.350,NaN,11.950,qual
19,20,Emma Lunn,Ireland,5.0,6.850,-0.1,11.750,qual
20,21,Teja Belak,Slovenia,5.5,6.150,NaN,11.650,qual
21,22,Inna Vassilyeva,Kazakhstan,4.7,6.550,NaN,11.250,qual
22,23,Nim Yan Choi,Hong Kong,4.4,6.700,NaN,11.100,qual
23,24,Ekaterina Kislinskaya,Portugal,4.5,6.600,NaN,11.100,qual
24,25,Miriam Fouad El Hajj,Egypt,5.2,5.900,NaN,11.100,qual
25,26,Maegan Chant,Canada,5.5,5.600,NaN,11.100,qual
26,27,Lisa Ecker,Austria,5.2,5.850,NaN,11.050,qual
27,28,Barbora Mokosova,Slovakia,4.8,6.150,NaN,10.950,qual
28,29,Ang Tracie,Malaysia,5.0,5.900,NaN,10.900,qual
29,30,India McPeak,Ireland,4.8,5.750,NaN,10.550,qual
30,31,Ivet Rojas,Venezuela,5.3,5.200,-0.1,10.400,qual
31,32,Jana Sikulova,Czech Republic,5.0,5.000,NaN,10.000,qual
32,33,Farida Ahmed Shokry,Egypt,4.1,5.550,NaN,9.650,qual
33,34,Paula Tiitta,Finland,4.5,5.150,NaN,9.650,qual

In [8]:
bb = combined_df.copy()

In [9]:
bb['year']=2013

In [10]:
bb['ND'].fillna(0, inplace=True)

In [11]:
bb['Nation'].unique()

array(['Russia', 'Greece', 'Netherlands', 'Spain', 'Portugal',
       'Uzbekistan', 'Czech Republic', 'China', 'Finland', 'Hong Kong',
       'Austria', 'Venezuela', 'Sweden', 'Germany', 'Ireland', 'Slovenia',
       'Kazakhstan', 'Egypt', 'Canada', 'Slovakia', 'Malaysia'],
      dtype=object)

In [12]:
# Define a mapping dictionary for nations and their NOC codes
nations_to_noc = {
    'Russia': 'RUS',
    'Greece': 'GRE',
    'Netherlands': 'NED',
    'Spain': 'ESP',
    'Portugal': 'POR',
    'Uzbekistan': 'UZB',
    'Czech Republic': 'CZE',
    'China': 'CHN',
    'Finland': 'FIN',
    'Hong Kong': 'HKG',
    'Austria': 'AUT',
    'Venezuela': 'VEN',
    'Sweden': 'SWE',
    'Germany': 'GER',
    'Ireland': 'IRL',
    'Slovenia': 'SLO',
    'Kazakhstan': 'KAZ',
    'Egypt': 'EGY',
    'Canada': 'CAN',
    'Slovakia': 'SVK',
    'Malaysia': 'MAS'
}

# Use the replace method to replace values in the "nations" column with NOC codes
bb['Nation'] = bb['Nation'].replace(nations_to_noc)

In [13]:
bb

    Rank                Athlete Nation    D      E   ND   Total  round  year
0      1     Anastasia Grishina    RUS  5.8  8.800  0.0  14.600  final  2013
1      2      Vasiliki Millousi    GRE  5.7  8.600  0.0  14.300  final  2013
2      3        Anna Dementyeva    RUS  6.0  8.275 -0.1  14.175  final  2013
3      4      Noel van Klaveren    NED  5.1  8.425  0.0  13.525  final  2013
4      5     Maria Paula Vargas    ESP  5.8  7.525  0.0  13.325  final  2013
5      6         Filipa Martins    POR  4.9  8.175  0.0  13.075  final  2013
6      7     Oksana Chusovitina    UZB  5.5  7.650 -0.1  13.050  final  2013
7      8   Dilnoza Abdusalimova    UZB  5.1  7.850 -0.1  12.850  final  2013
0      1     Anastasia Grishina    RUS  5.6  8.450  0.0  14.050   qual  2013
1      2      Noel van Klaveren    NED  5.4  8.450  0.0  13.850   qual  2013
2      3      Vasiliki Millousi    GRE  5.3  8.500  0.0  13.800   qual  2013
3      4     Oksana Chusovitina    UZB  5.4  8.250  0.0  13.650   qual  2013
4      5        Anna Dementyeva    RUS  6.1  7.550  0.0  13.650   qual  2013
5      6     Maria Paula Vargas    ESP  5.8  7.800  0.0  13.600   qual  2013
6      7         Filipa Martins    POR  5.3  8.500 -0.5  13.300   qual  2013
7      8   Dilnoza Abdusalimova    UZB  5.1  8.050 -0.1  13.050   qual  2013
8      9      Kristyna Palesova    CZE  5.3  7.700  0.0  13.000   qual  2013
9     10           Huang Huidan    CHN  5.7  7.400 -0.1  13.000   qual  2013
10    11         Maija Leinonen    FIN  4.9  8.000  0.0  12.900   qual  2013
11    12    Hiu Ying Angel Wong    HKG  4.6  8.200  0.0  12.800   qual  2013
12    13         Elisa HÃ¤mmerle    AUT  5.2  7.700 -0.1  12.800   qual  2013
13    14          Jessica Lopez    VEN  5.7  6.950  0.0  12.650   qual  2013
14    15  Silvia Colussi Pelaez    ESP  5.8  6.650  0.0  12.450   qual  2013
15    16       Chantysha Netteb    NED  5.0  7.350  0.0  12.350   qual  2013
16    17         Ida Gustafsson    SWE  5.3  6.900  0.0  12.200   qual  2013
17    18            Cagla Akyol    GER  5.5  6.550  0.0  12.050   qual  2013
18    19        Pauline SchÃ¤fer    GER  4.6  7.350  0.0  11.950   qual  2013
19    20              Emma Lunn    IRL  5.0  6.850 -0.1  11.750   qual  2013
20    21             Teja Belak    SLO  5.5  6.150  0.0  11.650   qual  2013
21    22        Inna Vassilyeva    KAZ  4.7  6.550  0.0  11.250   qual  2013
22    23           Nim Yan Choi    HKG  4.4  6.700  0.0  11.100   qual  2013
23    24  Ekaterina Kislinskaya    POR  4.5  6.600  0.0  11.100   qual  2013
24    25   Miriam Fouad El Hajj    EGY  5.2  5.900  0.0  11.100   qual  2013
25    26           Maegan Chant    CAN  5.5  5.600  0.0  11.100   qual  2013
26    27             Lisa Ecker    AUT  5.2  5.850  0.0  11.050   qual  2013
27    28       Barbora Mokosova    SVK  4.8  6.150  0.0  10.950   qual  2013
28    29             Ang Tracie    MAS  5.0  5.900  0.0  10.900   qual  2013
29    30           India McPeak    IRL  4.8  5.750  0.0  10.550   qual  2013
30    31             Ivet Rojas    VEN  5.3  5.200 -0.1  10.400   qual  2013
31    32          Jana Sikulova    CZE  5.0  5.000  0.0  10.000   qual  2013
32    33    Farida Ahmed Shokry    EGY  4.1  5.550  0.0   9.650   qual  2013
33    34           Paula Tiitta    FIN  4.5  5.150  0.0   9.650   qual  2013

In [14]:
bb.info()

<class 'pandas.core.frame.DataFrame'>
Index: 42 entries, 0 to 33
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     42 non-null     int64
 1   Athlete  42 non-null     object
 2   Nation   42 non-null     object
 3   D        42 non-null     float64
 4   E        42 non-null     float64
 5   ND       42 non-null     float64
 6   Total    42 non-null     float64
 7   round    42 non-null     object
 8   year     42 non-null     int64
dtypes: float64(4), int64(2), object(3)
memory usage: 3.3+ KB

In [15]:
ub = pd.read_csv('../../../scraping/women/worldcup13cott/worldcup2013cott_ub.csv')
ubq = pd.read_csv('../../../scraping/women/worldcup13cott/worldcup2013cott_ub_qual.csv')

In [16]:
ub['round']='final'

In [17]:
ubq['round']='qual'

In [18]:
combined_df = pd.concat([ub, ubq])

In [19]:
ub = combined_df.copy()

In [20]:
ub['year']=2013

In [21]:
ub['ND'].fillna(0, inplace=True)

In [22]:
ub['Nation'].unique()

array(['Russia', 'Venezuela', 'Spain', 'Czech Republic', 'Germany',
       'Portugal', 'Sweden', 'China', 'Netherlands', 'Austria',
       'Slovenia', 'Canada', 'Switzerland', 'Finland', 'Egypt',
       'Slovakia', 'Kazakhstan', 'Ireland', 'Malaysia'], dtype=object)

In [23]:
updated_nations_to_noc = {
    'Russia': 'RUS',
    'Venezuela': 'VEN',
    'Spain': 'ESP',
    'Czech Republic': 'CZE',
    'Germany': 'GER',
    'Portugal': 'POR',
    'Sweden': 'SWE',
    'China': 'CHN',
    'Netherlands': 'NED',
    'Austria': 'AUT',
    'Slovenia': 'SVN',
    'Canada': 'CAN',
    'Switzerland': 'SUI',
    'Finland': 'FIN',
    'Egypt': 'EGY',
    'Slovakia': 'SVK',
    'Kazakhstan': 'KAZ',
    'Ireland': 'IRL',
    'Malaysia': 'MAS'
}

# Use the replace method to replace values in the "nations" column with the updated NOC codes
ub['Nation'] = ub['Nation'].replace(updated_nations_to_noc)

In [24]:
ub.info()

<class 'pandas.core.frame.DataFrame'>
Index: 38 entries, 0 to 29
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     38 non-null     int64
 1   Athlete  38 non-null     object
 2   Nation   38 non-null     object
 3   D        38 non-null     float64
 4   E        38 non-null     float64
 5   ND       38 non-null     float64
 6   Total    38 non-null     float64
 7   round    38 non-null     object
 8   year     38 non-null     int64
dtypes: float64(4), int64(2), object(3)
memory usage: 3.0+ KB

In [25]:
fx = pd.read_csv('../../../scraping/women/worldcup13cott/worldcup2013cott_fx.csv')
fxq = pd.read_csv('../../../scraping/women/worldcup13cott/worldcup2013cott_fx_qual.csv')

In [26]:
fx['round']='final'

In [27]:
fxq['round']='qual'

In [28]:
combined_df = pd.concat([fx, fxq])

In [29]:
fx=combined_df.copy()

In [30]:
fx['year']=2013

In [31]:
fx['ND'].fillna(0, inplace=True)

In [32]:
fx['Nation'].unique()

array(['Canada', 'Russia', 'Netherlands', 'Germany', 'Venezuela', 'Spain',
       'Austria', 'Portugal', 'Czech Republic', 'Sweden', 'Uzbekistan',
       'Finland', 'Slovakia', 'Switzerland', 'Kazakhstan', 'Ireland',
       'Puerto Rico', 'Egypt', 'Malaysia'], dtype=object)

In [33]:
nations_to_noc = {
    'Canada': 'CAN',
    'Russia': 'RUS',
    'Netherlands': 'NED',
    'Germany': 'GER',
    'Venezuela': 'VEN',
    'Spain': 'ESP',
    'Austria': 'AUT',
    'Portugal': 'POR',
    'Czech Republic': 'CZE',
    'Sweden': 'SWE',
    'Uzbekistan': 'UZB',
    'Finland': 'FIN',
    'Slovakia': 'SVK',
    'Switzerland': 'SUI',
    'Kazakhstan': 'KAZ',
    'Ireland': 'IRL',
    'Puerto Rico': 'PUR',  
    'Egypt': 'EGY',
    'Malaysia': 'MAS'
}

# Use the replace method to replace values in the "nations" column with the provided NOC codes
fx['Nation'] = fx['Nation'].replace(nations_to_noc)

In [34]:
fx.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34 entries, 0 to 25
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     34 non-null     int64
 1   Athlete  34 non-null     object
 2   Nation   34 non-null     object
 3   D        34 non-null     float64
 4   E        34 non-null     float64
 5   ND       34 non-null     float64
 6   Total    34 non-null     float64
 7   round    34 non-null     object
 8   year     34 non-null     int64
dtypes: float64(4), int64(2), object(3)
memory usage: 2.7+ KB

In [35]:
vt = pd.read_csv('../../../scraping/women/worldcup13cott/worldcup2013cott_vt.csv')

In [36]:
vt['ND'].fillna(0,inplace=True)

In [37]:
vt['nd2'].fillna(0,inplace=True)

In [38]:
vt['Nation'].unique()

array(['Uzbekistan', 'Netherlands', 'Canada', 'Hong Kong', 'Chile',
       'Israel', 'Puerto Rico'], dtype=object)

In [39]:
nations_to_noc = {
    'Uzbekistan': 'UZB',
    'Netherlands': 'NED',
    'Canada': 'CAN',
    'Hong Kong': 'HKG',
    'Chile': 'CHI',  
    'Israel': 'ISR',  
    'Puerto Rico': 'PUR',
}

# Use the replace method to replace values in the "nations" column with the provided NOC codes
vt['Nation'] = vt['Nation'].replace(nations_to_noc)

In [40]:
vt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 12 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     8 non-null      int64
 1   Athlete  8 non-null      object
 2   Nation   8 non-null      object
 3   D        8 non-null      float64
 4   E        8 non-null      float64
 5   ND       8 non-null      float64
 6   Total    8 non-null      float64
 7   d2       8 non-null      float64
 8   e2       8 non-null      float64
 9   nd2      8 non-null      float64
 10  total2   8 non-null      float64
 11  Average  8 non-null      float64
dtypes: float64(9), int64(1), object(2)
memory usage: 896.0+ bytes

In [41]:
fx.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34 entries, 0 to 25
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     34 non-null     int64
 1   Athlete  34 non-null     object
 2   Nation   34 non-null     object
 3   D        34 non-null     float64
 4   E        34 non-null     float64
 5   ND       34 non-null     float64
 6   Total    34 non-null     float64
 7   round    34 non-null     object
 8   year     34 non-null     int64
dtypes: float64(4), int64(2), object(3)
memory usage: 2.7+ KB

In [42]:
ub.info()

<class 'pandas.core.frame.DataFrame'>
Index: 38 entries, 0 to 29
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     38 non-null     int64
 1   Athlete  38 non-null     object
 2   Nation   38 non-null     object
 3   D        38 non-null     float64
 4   E        38 non-null     float64
 5   ND       38 non-null     float64
 6   Total    38 non-null     float64
 7   round    38 non-null     object
 8   year     38 non-null     int64
dtypes: float64(4), int64(2), object(3)
memory usage: 3.0+ KB

In [43]:
bb.info()

<class 'pandas.core.frame.DataFrame'>
Index: 42 entries, 0 to 33
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     42 non-null     int64
 1   Athlete  42 non-null     object
 2   Nation   42 non-null     object
 3   D        42 non-null     float64
 4   E        42 non-null     float64
 5   ND       42 non-null     float64
 6   Total    42 non-null     float64
 7   round    42 non-null     object
 8   year     42 non-null     int64
dtypes: float64(4), int64(2), object(3)
memory usage: 3.3+ KB

In [44]:
# vt.to_csv('clean_wc13cott_vt.csv', index=False)
# fx.to_csv('clean_wc13cott_fx.csv', index=False)
# ub.to_csv('clean_wc13cott_ub.csv', index=False)
# bb.to_csv('clean_wc13cott_bb.csv', index=False)