In [39]:
import pandas as pd
import numpy as np

In [40]:
wc11 = pd.read_csv('wc11vt.csv')
wc13 = pd.read_csv('wc13vt.csv')
wc14 = pd.read_csv('wc14vt.csv')
wc15 = pd.read_csv('wc15vt.csv')
wc17 = pd.read_csv('wc17vt.csv')
wc18 = pd.read_csv('wc18vt.csv')
wc19 = pd.read_csv('wc19vt.csv')

In [41]:
wc11 = wc11.drop(columns=["Rk1", "Rk2"])

In [42]:
wc11.rename(columns={'Position': 'Rank'}, inplace=True)

In [43]:
wc11.head(1)

,Rank,Gymnast,D Score1,E Score1,Pen.1,Score 1,D Score2,E Score2,Pen.2,Score 2,Total,year
0,1,McKayla Maroney(USA),6.5,9.3,0.0,15.8,5.6,9.2,0.0,14.8,15.3,2011

In [44]:
wc13.head(1)

,Rank,Gymnast,D Score1,E Score1,Pen.1,Score 1,D Score2,E Score2,Pen.2,Score 2,Total,year
0,1,McKayla Maroney(USA),6.3,9.766,0.1,15.966,6.0,9.483,0.0,15.483,15.724,2013

In [45]:
wc14.head(1)

,Rank,Gymnast,D Score1,E Score1,Pen.1,Score 1,D Score2,E Score2,Pen.2,Score 2,Total,year
0,1,Hong Un-jong(PRK),6.3,9.466,0.0,15.766,6.4,9.033,0.0,15.433,15.599,2014

In [46]:
wc15.rename(columns={'Position': 'Rank', 'Total2':'Total'}, inplace=True)

In [47]:
wc15.head(1)

,Rank,Gymnast,D Score1,E Score1,Pen.1,Score 1,D Score2,E Score2,Pen.2,Score 2,Total,year
0,1,Maria Paseka(RUS),6.4,9.233,0.0,15.633,6.3,9.4,0.0,15.7,15.666,2015

In [48]:
wc17.rename(columns={'Position': 'Rank', 'score2':'Score 2'}, inplace=True)

In [49]:
wc17.head(1)

,Rank,Gymnast,D Score1,E Score1,Pen.1,Score 1,D Score2,E Score2,Pen.2,Score 2,Total,year
0,1,Maria Paseka,6.0,8.7,0.0,14.7,5.8,9.2,0.0,15.0,14.85,2017

In [50]:
wc18.rename(columns={'Position': 'Rank'}, inplace=True)

In [51]:
wc18.head(1)

,Rank,Gymnast,D Score1,E Score1,Pen.1,Score 1,D Score2,E Score2,Pen.2,Score 2,Total,year
0,0.0,Simone Biles,6.0,9.266,0.0,15.266,5.8,9.666,0.0,15.466,15.366,2018

In [52]:
wc19.rename(columns={'Position': 'Rank', 'total':'Total'}, inplace=True)

In [53]:
wc19.head(1)

,Rank,Gymnast,D Score1,E Score1,Pen.1,Score 1,D Score2,E Score2,Pen.2,Score 2,Total,year
0,1,Simone Biles,6.0,9.333,0.0,15.333,5.8,9.666,0.0,15.466,15.399,2019

In [54]:
combined_df = pd.concat([wc11, wc13, wc14, wc15, wc17, wc18, wc19], axis=0)

In [75]:
combined_df.head(8)

,Rank,Gymnast,D Score1,E Score1,Pen.1,Score 1,D Score2,E Score2,Pen.2,Score 2,Total,year
0,1.0,McKayla Maroney(USA),6.5,9.300,0.0,15.800,5.6,9.200,0.0,14.800,15.300,2011
1,2.0,Oksana Chusovitina(GER),6.3,8.766,0.0,15.066,5.5,8.900,0.0,14.333,14.733,2011
2,3.0,Phan Thị Hà Thanh(VIE),5.9,8.700,0.0,14.600,5.8,8.933,0.0,14.733,14.666,2011
3,4.0,Jade Barbosa(BRA),5.8,9.066,0.0,14.866,5.6,8.666,0.0,14.266,14.566,2011
4,5.0,Giulia Steingruber(SUI),6.3,8.600,0.0,14.900,5.2,8.800,0.0,14.000,14.450,2011
5,6.0,Tatiana Nabieva(RUS),5.8,8.766,0.0,14.566,5.2,8.933,0.0,14.133,14.349,2011
6,7.0,Alexa Moreno(MEX),6.3,8.433,0.0,14.733,5.2,8.500,0.0,13.700,14.216,2011
7,8.0,Yamilet Peña(DOM),5.3,8.600,0.0,13.900,0.000*,0.000,0.0,0.000,6.950,2011

In [99]:
df=combined_df.copy()

In [100]:
# Function to remove asterisk (*) from a string
def remove_asterisk(value):
    return value.replace('*', '')

# Apply the remove_asterisk function to the specific cell
row_index_to_update = 7
df.at[row_index_to_update, 'D Score2'] = remove_asterisk(df.at[row_index_to_update, 'D Score2'])

In [111]:
df.loc[7, 'D Score2'] = 0.000

In [112]:
df

,Rank,Gymnast,D Score1,E Score1,Pen.1,Score 1,D Score2,E Score2,Pen.2,Score 2,Total,year
0,1.0,McKayla Maroney(USA),6.5,9.300,0.0,15.800,5.6,9.200,0.0,14.800,15.300,2011
1,2.0,Oksana Chusovitina(GER),6.3,8.766,0.0,15.066,5.5,8.900,0.0,14.333,14.733,2011
2,3.0,Phan Thị Hà Thanh(VIE),5.9,8.700,0.0,14.600,5.8,8.933,0.0,14.733,14.666,2011
3,4.0,Jade Barbosa(BRA),5.8,9.066,0.0,14.866,5.6,8.666,0.0,14.266,14.566,2011
4,5.0,Giulia Steingruber(SUI),6.3,8.600,0.0,14.900,5.2,8.800,0.0,14.000,14.450,2011
5,6.0,Tatiana Nabieva(RUS),5.8,8.766,0.0,14.566,5.2,8.933,0.0,14.133,14.349,2011
6,7.0,Alexa Moreno(MEX),6.3,8.433,0.0,14.733,5.2,8.500,0.0,13.700,14.216,2011
7,8.0,Yamilet Peña(DOM),5.3,8.600,0.0,13.900,0.0,0.000,0.0,0.000,6.950,2011
0,1.0,McKayla Maroney(USA),6.3,9.766,0.1,15.966,6.0,9.483,0.0,15.483,15.724,2013
1,2.0,Simone Biles(USA),6.3,9.633,0.0,15.933,5.6,9.658,0.0,15.258,15.595,2013
2,3.0,Hong Un-Jong(PRK),6.3,9.266,0.0,15.566,6.4,9.000,0.0,15.400,15.483,2013
3,4.0,Giulia Steingruber(SUI),6.2,9.300,0.0,15.500,5.8,9.166,0.0,14.966,15.233,2013
4,5.0,Oksana Chusovitina(UZB),6.2,8.533,0.1,14.633,5.5,9.033,0.0,14.533,14.583,2013
5,6.0,Phan Thị Hà Thanh(VIE),6.2,8.866,0.1,14.966,5.8,7.933,0.1,13.633,14.299,2013
6,7.0,Yamilet Peña(DOM),7.0,7.766,0.3,14.466,5.8,7.666,0.0,13.466,13.966,2013
7,8.0,Chantysha Netteb(NED),5.8,8.100,0.0,13.900,0.0,0.000,0.0,0.000,6.950,2013
0,1.0,Hong Un-jong(PRK),6.3,9.466,0.0,15.766,6.4,9.033,0.0,15.433,15.599,2014
1,2.0,Simone Biles(USA),6.3,9.600,0.0,15.900,5.6,9.608,0.0,15.208,15.554,2014
2,3.0,Mykayla Skinner(USA),6.4,9.300,0.0,15.700,5.8,9.233,0.0,15.033,15.366,2014
3,4.0,Alla Sosnitskaya(RUS),6.4,8.866,0.3,14.966,5.8,9.166,0.0,14.966,14.966,2014
4,5.0,Giulia Steingruber(SUI),6.2,9.033,0.0,15.233,5.0,9.200,0.0,14.200,14.716,2014
5,5.0,Claudia Fragapane(GBR),5.8,9.033,0.0,14.833,5.6,9.000,0.0,14.600,14.716,2014
6,7.0,Alexa Moreno(MEX),6.2,8.833,0.0,15.033,6.0,8.366,0.3,14.066,14.549,2014
7,8.0,Phan Thị Hà Thanh(VIE),5.8,8.608,0.3,14.108,0.0,8.533,0.1,14.633,14.370,2014
0,1.0,Maria Paseka(RUS),6.4,9.233,0.0,15.633,6.3,9.400,0.0,15.700,15.666,2015
1,2.0,Hong Un-jong(PRK),6.3,9.366,0.0,15.666,6.4,9.200,0.0,15.600,15.633,2015
2,3.0,Simone Biles(USA),6.3,9.600,0.0,15.900,5.6,9.583,0.0,15.183,15.541,2015
3,4.0,Ellie Downie(GBR),5.8,9.166,0.0,14.966,5.6,9.233,0.0,14.833,14.899,2015
4,5.0,Dipa Karmakar(IND),7.0,8.300,0.0,15.300,6.0,8.366,-0.3,14.066,14.683,2015
5,6.0,Wang Yan(CHN),6.0,9.066,0.0,15.066,6.2,7.900,0.0,14.100,14.583,2015
6,7.0,Giulia Steingruber(SUI),6.2,9.400,-0.1,15.500,5.3,8.333,0.0,13.633,14.566,2015
7,7.0,Alexa Moreno(MEX),6.2,8.566,-0.1,14.666,0.0,8.566,-0.1,14.466,14.566,2015
0,1.0,Maria Paseka,6.0,8.700,0.0,14.700,5.8,9.200,0.0,15.000,14.850,2017
1,2.0,Jade Carey,5.8,9.000,0.0,14.800,5.6,9.133,0.0,14.733,14.766,2017
2,3.0,Giulia Steingruber,5.8,8.933,-0.1,14.633,5.4,8.900,0.0,14.300,14.466,2017
3,4.0,Ellie Black,5.4,9.166,0.0,14.566,5.2,9.066,0.0,14.266,14.416,2017
4,5.0,Oksana Chusovitina,5.4,9.033,0.0,14.433,5.2,9.100,0.0,14.300,14.366,2017
5,6.0,Wang Yan,5.6,8.900,0.0,14.500,5.8,8.500,-0.1,14.200,14.350,2017
6,7.0,Shallon Olsen,5.8,7.833,-0.1,13.533,6.0,8.933,0.0,14.933,14.233,2017
7,8.0,Sae Miyakawa,5.8,8.700,0.0,14.500,0.0,7.700,0.0,13.100,13.800,2017
0,0.0,Simone Biles,6.0,9.266,0.0,15.266,5.8,9.666,0.0,15.466,15.366,2018
1,0.0,Shallon Olsen,6.0,8.600,0.0,14.600,5.4,9.033,0.0,14.433,14.516,2018
2,0.0,Alexa Moreno,5.8,8.800,0.0,14.600,5.6,8.916,0.1,14.416,14.508,2018
3,4.0,Oksana Chusovitina,5.8,8.600,0.0,14.400,5.2,9.000,0.0,14.200,14.300,2018
4,5.0,Yeo Seo-jeong,5.8,8.833,0.1,14.533,5.4,8.533,0.0,13.933,14.233,2018
5,6.0,Liu Jinru,5.6,8.600,0.1,14.100,5.8,8.400,0.0,14.200,14.150,2018
6,7.0,Ellie Black,5.4,8.600,0.0,14.000,5.2,9.033,0.0,14.233,14.116,2018
7,8.0,Pyon Rye-yong,5.8,7.566,0.3,13.066,0.0,8.366,0.0,14.166,13.616,2018
0,1.0,Simone Biles,6.0,9.333,0.0,15.333,5.8,9.666,0.0,15.466,15.399,2019
1,2.0,Jade Carey,6.0,9.166,0.0,15.166,5.8,9.100,0.3,14.600,14.883,2019
2,3.0,Ellie Downie,5.4,9.200,0.0,14.600,6.0,9.033,0.0,15.033,14.816,2019
3,4.0,Shallon Olsen,5.4,9.200,0.0,14.600,6.0,8.866,0.0,14.866,14.733,2019
4,5.0,Qi Qi,5.4,9.200,0.0,14.600,5.8,8.900,0.0,14.700,14.650,2019
5,6.0,Alexa Moreno,5.8,8.766,0.1,14.466,5.6,9.200,0.0,14.800,14.633,2019
6,7.0,Lilia Akhaimova,5.8,8.900,0.0,14.700,5.6,8.733,0.3,14.033,14.366,2019
7,8.0,Yeo Seo-jeong,6.2,8.033,0.3,13.933,0.0,9.033,0.0,14.433,14.183,2019

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 56 entries, 0 to 7
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Rank      56 non-null     float64
 1   Gymnast   56 non-null     object
 2   D Score1  56 non-null     float64
 3   E Score1  56 non-null     float64
 4   Pen.1     56 non-null     float64
 5   Score 1   56 non-null     float64
 6   D Score2  56 non-null     object
 7   E Score2  56 non-null     float64
 8   Pen.2     56 non-null     float64
 9   Score 2   56 non-null     float64
 10  Total     56 non-null     float64
 11  year      56 non-null     int64
dtypes: float64(9), int64(1), object(2)
memory usage: 7.7+ KB

In [114]:
df['D Score2'] = df['D Score2'].astype(float)

In [115]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 56 entries, 0 to 7
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Rank      56 non-null     float64
 1   Gymnast   56 non-null     object
 2   D Score1  56 non-null     float64
 3   E Score1  56 non-null     float64
 4   Pen.1     56 non-null     float64
 5   Score 1   56 non-null     float64
 6   D Score2  56 non-null     float64
 7   E Score2  56 non-null     float64
 8   Pen.2     56 non-null     float64
 9   Score 2   56 non-null     float64
 10  Total     56 non-null     float64
 11  year      56 non-null     int64
dtypes: float64(10), int64(1), object(1)
memory usage: 7.7+ KB

In [116]:
df

,Rank,Gymnast,D Score1,E Score1,Pen.1,Score 1,D Score2,E Score2,Pen.2,Score 2,Total,year
0,1.0,McKayla Maroney(USA),6.5,9.300,0.0,15.800,5.6,9.200,0.0,14.800,15.300,2011
1,2.0,Oksana Chusovitina(GER),6.3,8.766,0.0,15.066,5.5,8.900,0.0,14.333,14.733,2011
2,3.0,Phan Thị Hà Thanh(VIE),5.9,8.700,0.0,14.600,5.8,8.933,0.0,14.733,14.666,2011
3,4.0,Jade Barbosa(BRA),5.8,9.066,0.0,14.866,5.6,8.666,0.0,14.266,14.566,2011
4,5.0,Giulia Steingruber(SUI),6.3,8.600,0.0,14.900,5.2,8.800,0.0,14.000,14.450,2011
5,6.0,Tatiana Nabieva(RUS),5.8,8.766,0.0,14.566,5.2,8.933,0.0,14.133,14.349,2011
6,7.0,Alexa Moreno(MEX),6.3,8.433,0.0,14.733,5.2,8.500,0.0,13.700,14.216,2011
7,8.0,Yamilet Peña(DOM),5.3,8.600,0.0,13.900,0.0,0.000,0.0,0.000,6.950,2011
0,1.0,McKayla Maroney(USA),6.3,9.766,0.1,15.966,6.0,9.483,0.0,15.483,15.724,2013
1,2.0,Simone Biles(USA),6.3,9.633,0.0,15.933,5.6,9.658,0.0,15.258,15.595,2013
2,3.0,Hong Un-Jong(PRK),6.3,9.266,0.0,15.566,6.4,9.000,0.0,15.400,15.483,2013
3,4.0,Giulia Steingruber(SUI),6.2,9.300,0.0,15.500,5.8,9.166,0.0,14.966,15.233,2013
4,5.0,Oksana Chusovitina(UZB),6.2,8.533,0.1,14.633,5.5,9.033,0.0,14.533,14.583,2013
5,6.0,Phan Thị Hà Thanh(VIE),6.2,8.866,0.1,14.966,5.8,7.933,0.1,13.633,14.299,2013
6,7.0,Yamilet Peña(DOM),7.0,7.766,0.3,14.466,5.8,7.666,0.0,13.466,13.966,2013
7,8.0,Chantysha Netteb(NED),5.8,8.100,0.0,13.900,0.0,0.000,0.0,0.000,6.950,2013
0,1.0,Hong Un-jong(PRK),6.3,9.466,0.0,15.766,6.4,9.033,0.0,15.433,15.599,2014
1,2.0,Simone Biles(USA),6.3,9.600,0.0,15.900,5.6,9.608,0.0,15.208,15.554,2014
2,3.0,Mykayla Skinner(USA),6.4,9.300,0.0,15.700,5.8,9.233,0.0,15.033,15.366,2014
3,4.0,Alla Sosnitskaya(RUS),6.4,8.866,0.3,14.966,5.8,9.166,0.0,14.966,14.966,2014
4,5.0,Giulia Steingruber(SUI),6.2,9.033,0.0,15.233,5.0,9.200,0.0,14.200,14.716,2014
5,5.0,Claudia Fragapane(GBR),5.8,9.033,0.0,14.833,5.6,9.000,0.0,14.600,14.716,2014
6,7.0,Alexa Moreno(MEX),6.2,8.833,0.0,15.033,6.0,8.366,0.3,14.066,14.549,2014
7,8.0,Phan Thị Hà Thanh(VIE),5.8,8.608,0.3,14.108,0.0,8.533,0.1,14.633,14.370,2014
0,1.0,Maria Paseka(RUS),6.4,9.233,0.0,15.633,6.3,9.400,0.0,15.700,15.666,2015
1,2.0,Hong Un-jong(PRK),6.3,9.366,0.0,15.666,6.4,9.200,0.0,15.600,15.633,2015
2,3.0,Simone Biles(USA),6.3,9.600,0.0,15.900,5.6,9.583,0.0,15.183,15.541,2015
3,4.0,Ellie Downie(GBR),5.8,9.166,0.0,14.966,5.6,9.233,0.0,14.833,14.899,2015
4,5.0,Dipa Karmakar(IND),7.0,8.300,0.0,15.300,6.0,8.366,-0.3,14.066,14.683,2015
5,6.0,Wang Yan(CHN),6.0,9.066,0.0,15.066,6.2,7.900,0.0,14.100,14.583,2015
6,7.0,Giulia Steingruber(SUI),6.2,9.400,-0.1,15.500,5.3,8.333,0.0,13.633,14.566,2015
7,7.0,Alexa Moreno(MEX),6.2,8.566,-0.1,14.666,0.0,8.566,-0.1,14.466,14.566,2015
0,1.0,Maria Paseka,6.0,8.700,0.0,14.700,5.8,9.200,0.0,15.000,14.850,2017
1,2.0,Jade Carey,5.8,9.000,0.0,14.800,5.6,9.133,0.0,14.733,14.766,2017
2,3.0,Giulia Steingruber,5.8,8.933,-0.1,14.633,5.4,8.900,0.0,14.300,14.466,2017
3,4.0,Ellie Black,5.4,9.166,0.0,14.566,5.2,9.066,0.0,14.266,14.416,2017
4,5.0,Oksana Chusovitina,5.4,9.033,0.0,14.433,5.2,9.100,0.0,14.300,14.366,2017
5,6.0,Wang Yan,5.6,8.900,0.0,14.500,5.8,8.500,-0.1,14.200,14.350,2017
6,7.0,Shallon Olsen,5.8,7.833,-0.1,13.533,6.0,8.933,0.0,14.933,14.233,2017
7,8.0,Sae Miyakawa,5.8,8.700,0.0,14.500,0.0,7.700,0.0,13.100,13.800,2017
0,0.0,Simone Biles,6.0,9.266,0.0,15.266,5.8,9.666,0.0,15.466,15.366,2018
1,0.0,Shallon Olsen,6.0,8.600,0.0,14.600,5.4,9.033,0.0,14.433,14.516,2018
2,0.0,Alexa Moreno,5.8,8.800,0.0,14.600,5.6,8.916,0.1,14.416,14.508,2018
3,4.0,Oksana Chusovitina,5.8,8.600,0.0,14.400,5.2,9.000,0.0,14.200,14.300,2018
4,5.0,Yeo Seo-jeong,5.8,8.833,0.1,14.533,5.4,8.533,0.0,13.933,14.233,2018
5,6.0,Liu Jinru,5.6,8.600,0.1,14.100,5.8,8.400,0.0,14.200,14.150,2018
6,7.0,Ellie Black,5.4,8.600,0.0,14.000,5.2,9.033,0.0,14.233,14.116,2018
7,8.0,Pyon Rye-yong,5.8,7.566,0.3,13.066,0.0,8.366,0.0,14.166,13.616,2018
0,1.0,Simone Biles,6.0,9.333,0.0,15.333,5.8,9.666,0.0,15.466,15.399,2019
1,2.0,Jade Carey,6.0,9.166,0.0,15.166,5.8,9.100,0.3,14.600,14.883,2019
2,3.0,Ellie Downie,5.4,9.200,0.0,14.600,6.0,9.033,0.0,15.033,14.816,2019
3,4.0,Shallon Olsen,5.4,9.200,0.0,14.600,6.0,8.866,0.0,14.866,14.733,2019
4,5.0,Qi Qi,5.4,9.200,0.0,14.600,5.8,8.900,0.0,14.700,14.650,2019
5,6.0,Alexa Moreno,5.8,8.766,0.1,14.466,5.6,9.200,0.0,14.800,14.633,2019
6,7.0,Lilia Akhaimova,5.8,8.900,0.0,14.700,5.6,8.733,0.3,14.033,14.366,2019
7,8.0,Yeo Seo-jeong,6.2,8.033,0.3,13.933,0.0,9.033,0.0,14.433,14.183,2019

In [117]:
df['Gymnast'] = df['Gymnast'].str.replace(r'\(.*\)', '', regex=True)

In [118]:
df

,Rank,Gymnast,D Score1,E Score1,Pen.1,Score 1,D Score2,E Score2,Pen.2,Score 2,Total,year
0,1.0,McKayla Maroney,6.5,9.300,0.0,15.800,5.6,9.200,0.0,14.800,15.300,2011
1,2.0,Oksana Chusovitina,6.3,8.766,0.0,15.066,5.5,8.900,0.0,14.333,14.733,2011
2,3.0,Phan Thị Hà Thanh,5.9,8.700,0.0,14.600,5.8,8.933,0.0,14.733,14.666,2011
3,4.0,Jade Barbosa,5.8,9.066,0.0,14.866,5.6,8.666,0.0,14.266,14.566,2011
4,5.0,Giulia Steingruber,6.3,8.600,0.0,14.900,5.2,8.800,0.0,14.000,14.450,2011
5,6.0,Tatiana Nabieva,5.8,8.766,0.0,14.566,5.2,8.933,0.0,14.133,14.349,2011
6,7.0,Alexa Moreno,6.3,8.433,0.0,14.733,5.2,8.500,0.0,13.700,14.216,2011
7,8.0,Yamilet Peña,5.3,8.600,0.0,13.900,0.0,0.000,0.0,0.000,6.950,2011
0,1.0,McKayla Maroney,6.3,9.766,0.1,15.966,6.0,9.483,0.0,15.483,15.724,2013
1,2.0,Simone Biles,6.3,9.633,0.0,15.933,5.6,9.658,0.0,15.258,15.595,2013
2,3.0,Hong Un-Jong,6.3,9.266,0.0,15.566,6.4,9.000,0.0,15.400,15.483,2013
3,4.0,Giulia Steingruber,6.2,9.300,0.0,15.500,5.8,9.166,0.0,14.966,15.233,2013
4,5.0,Oksana Chusovitina,6.2,8.533,0.1,14.633,5.5,9.033,0.0,14.533,14.583,2013
5,6.0,Phan Thị Hà Thanh,6.2,8.866,0.1,14.966,5.8,7.933,0.1,13.633,14.299,2013
6,7.0,Yamilet Peña,7.0,7.766,0.3,14.466,5.8,7.666,0.0,13.466,13.966,2013
7,8.0,Chantysha Netteb,5.8,8.100,0.0,13.900,0.0,0.000,0.0,0.000,6.950,2013
0,1.0,Hong Un-jong,6.3,9.466,0.0,15.766,6.4,9.033,0.0,15.433,15.599,2014
1,2.0,Simone Biles,6.3,9.600,0.0,15.900,5.6,9.608,0.0,15.208,15.554,2014
2,3.0,Mykayla Skinner,6.4,9.300,0.0,15.700,5.8,9.233,0.0,15.033,15.366,2014
3,4.0,Alla Sosnitskaya,6.4,8.866,0.3,14.966,5.8,9.166,0.0,14.966,14.966,2014
4,5.0,Giulia Steingruber,6.2,9.033,0.0,15.233,5.0,9.200,0.0,14.200,14.716,2014
5,5.0,Claudia Fragapane,5.8,9.033,0.0,14.833,5.6,9.000,0.0,14.600,14.716,2014
6,7.0,Alexa Moreno,6.2,8.833,0.0,15.033,6.0,8.366,0.3,14.066,14.549,2014
7,8.0,Phan Thị Hà Thanh,5.8,8.608,0.3,14.108,0.0,8.533,0.1,14.633,14.370,2014
0,1.0,Maria Paseka,6.4,9.233,0.0,15.633,6.3,9.400,0.0,15.700,15.666,2015
1,2.0,Hong Un-jong,6.3,9.366,0.0,15.666,6.4,9.200,0.0,15.600,15.633,2015
2,3.0,Simone Biles,6.3,9.600,0.0,15.900,5.6,9.583,0.0,15.183,15.541,2015
3,4.0,Ellie Downie,5.8,9.166,0.0,14.966,5.6,9.233,0.0,14.833,14.899,2015
4,5.0,Dipa Karmakar,7.0,8.300,0.0,15.300,6.0,8.366,-0.3,14.066,14.683,2015
5,6.0,Wang Yan,6.0,9.066,0.0,15.066,6.2,7.900,0.0,14.100,14.583,2015
6,7.0,Giulia Steingruber,6.2,9.400,-0.1,15.500,5.3,8.333,0.0,13.633,14.566,2015
7,7.0,Alexa Moreno,6.2,8.566,-0.1,14.666,0.0,8.566,-0.1,14.466,14.566,2015
0,1.0,Maria Paseka,6.0,8.700,0.0,14.700,5.8,9.200,0.0,15.000,14.850,2017
1,2.0,Jade Carey,5.8,9.000,0.0,14.800,5.6,9.133,0.0,14.733,14.766,2017
2,3.0,Giulia Steingruber,5.8,8.933,-0.1,14.633,5.4,8.900,0.0,14.300,14.466,2017
3,4.0,Ellie Black,5.4,9.166,0.0,14.566,5.2,9.066,0.0,14.266,14.416,2017
4,5.0,Oksana Chusovitina,5.4,9.033,0.0,14.433,5.2,9.100,0.0,14.300,14.366,2017
5,6.0,Wang Yan,5.6,8.900,0.0,14.500,5.8,8.500,-0.1,14.200,14.350,2017
6,7.0,Shallon Olsen,5.8,7.833,-0.1,13.533,6.0,8.933,0.0,14.933,14.233,2017
7,8.0,Sae Miyakawa,5.8,8.700,0.0,14.500,0.0,7.700,0.0,13.100,13.800,2017
0,0.0,Simone Biles,6.0,9.266,0.0,15.266,5.8,9.666,0.0,15.466,15.366,2018
1,0.0,Shallon Olsen,6.0,8.600,0.0,14.600,5.4,9.033,0.0,14.433,14.516,2018
2,0.0,Alexa Moreno,5.8,8.800,0.0,14.600,5.6,8.916,0.1,14.416,14.508,2018
3,4.0,Oksana Chusovitina,5.8,8.600,0.0,14.400,5.2,9.000,0.0,14.200,14.300,2018
4,5.0,Yeo Seo-jeong,5.8,8.833,0.1,14.533,5.4,8.533,0.0,13.933,14.233,2018
5,6.0,Liu Jinru,5.6,8.600,0.1,14.100,5.8,8.400,0.0,14.200,14.150,2018
6,7.0,Ellie Black,5.4,8.600,0.0,14.000,5.2,9.033,0.0,14.233,14.116,2018
7,8.0,Pyon Rye-yong,5.8,7.566,0.3,13.066,0.0,8.366,0.0,14.166,13.616,2018
0,1.0,Simone Biles,6.0,9.333,0.0,15.333,5.8,9.666,0.0,15.466,15.399,2019
1,2.0,Jade Carey,6.0,9.166,0.0,15.166,5.8,9.100,0.3,14.600,14.883,2019
2,3.0,Ellie Downie,5.4,9.200,0.0,14.600,6.0,9.033,0.0,15.033,14.816,2019
3,4.0,Shallon Olsen,5.4,9.200,0.0,14.600,6.0,8.866,0.0,14.866,14.733,2019
4,5.0,Qi Qi,5.4,9.200,0.0,14.600,5.8,8.900,0.0,14.700,14.650,2019
5,6.0,Alexa Moreno,5.8,8.766,0.1,14.466,5.6,9.200,0.0,14.800,14.633,2019
6,7.0,Lilia Akhaimova,5.8,8.900,0.0,14.700,5.6,8.733,0.3,14.033,14.366,2019
7,8.0,Yeo Seo-jeong,6.2,8.033,0.3,13.933,0.0,9.033,0.0,14.433,14.183,2019

In [119]:
# df.to_csv('wc11_19w_vt.csv', index=False)