In [12]:
import pandas as pd
import numpy as np

In [13]:
wc19melb = pd.read_csv('../../Cleaning/qual_events/men/wc19bmelb_pb.csv')
wc20baku = pd.read_csv('../../Cleaning/qual_events/men/wc20baku_pb.csv')
world18 = pd.read_csv('../../Cleaning/qual_events/men/world18championship_pb.csv')
world19cup = pd.read_csv('../../Cleaning/qual_events/men/world19cup_pb.csv')
wc19bmelb = pd.read_csv('../../Cleaning/qual_events/men/wc19bmelb_pb.csv')

winter20cup = pd.read_csv('../../Cleaning/qual_events/men/winter20cup_pb.csv')

In [14]:
pb = pd.concat([wc19melb, wc20baku, world18, world19cup, wc19bmelb])

In [15]:
pb

    Rank               Athlete Nation    D      E   ND   Total  year  round
0      1               you hao    CHN  6.8  8.266  0.0  15.066  2019  final
1      2           ahmet önder    TUR  6.2  8.433  0.0  14.633  2019  final
2      3         ferhat arican    TUR  6.5  7.866  0.0  14.366  2019  final
3      4      mitchell morgans    AUS  6.0  8.200  0.0  14.200  2019  final
4      5     hibiki arayashiki    JPN  5.9  8.166  0.0  14.066  2019  final
..   ...                   ...    ...  ...    ...  ...     ...   ...    ...
16     9            tyson bull    AUS  5.4  7.966  0.0  13.366  2019   qual
17    10          milad karimi    KAZ  5.7  7.533  0.0  13.233  2019   qual
18    11  valgard reinhardsson    ISL  4.9  8.200  0.0  13.100  2019   qual
19    12          bram louwije    NED  5.5  6.900  0.0  12.400  2019   qual
20    13        tang chia-hung   none  5.0  6.100  0.0  11.100  2019   qual

[470 rows x 9 columns]

In [8]:
desired_order = ['Rank', 'Athlete', 'Nation', 'D', 'E', 'ND', 'Total', 'year', 'round']

# Rearrange the columns in-place
winter20cup = winter20cup[desired_order]

In [9]:
pb = pd.concat([pb, winter20cup])

In [10]:
pb.info()

<class 'pandas.core.frame.DataFrame'>
Index: 506 entries, 0 to 35
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     506 non-null    int64
 1   Athlete  506 non-null    object
 2   Nation   505 non-null    object
 3   D        506 non-null    float64
 4   E        506 non-null    float64
 5   ND       506 non-null    float64
 6   Total    506 non-null    float64
 7   year     506 non-null    int64
 8   round    506 non-null    object
dtypes: float64(4), int64(2), object(3)
memory usage: 39.5+ KB

In [11]:
# pb.to_csv('pb.csv', index=False)