In [1]:
import pandas as pd
import numpy as np

In [2]:
fx = pd.read_csv('../../../scraping/men/world_champis2019/fx.csv')
fxq = pd.read_csv('../../../scraping/men/world_champis2019/fxq.csv')

hb = pd.read_csv('../../../scraping/men/world_champis2019/hb.csv')
hbq = pd.read_csv('../../../scraping/men/world_champis2019/hbq.csv')

ph = pd.read_csv('../../../scraping/men/world_champis2019/ph.csv')
phq = pd.read_csv('../../../scraping/men/world_champis2019/phq.csv')

pb = pd.read_csv('../../../scraping/men/world_champis2019/pb.csv')
pbq = pd.read_csv('../../../scraping/men/world_champis2019/pbq.csv')

sr = pd.read_csv('../../../scraping/men/world_champis2019/sr.csv')
srq = pd.read_csv('../../../scraping/men/world_champis2019/srq.csv')

iaa = pd.read_csv('../../../scraping/men/world_champis2019/iaa.csv')
iaaq = pd.read_csv('../../../scraping/men/world_champis2019/iaaq.csv')

In [3]:
pbq

     Rank           Athlete         Nation    D      E   ND   Total
0       1      Lukas Dauser        Germany  6.3  8.733  NaN  15.033
1       2    Petro Pakhniuk        Ukraine  6.5  8.533  NaN  15.033
2       3        Joe Fraser  Great Britain  6.6  8.400  NaN  15.000
3       4      Xiao Ruoteng          China  6.2  8.766  NaN  14.966
4       5     Ferhat Arican         Turkey  6.5  8.433  NaN  14.933
..    ...               ...            ...  ...    ...  ...     ...
187   188   Manuel Martinez       Colombia  5.2  5.133 -0.3  10.033
188   189   Yerbol Jantykov     Kazakhstan  4.6  4.966  NaN   9.566
189   190     Nabil Zouhair        Morocco  3.0  6.266  NaN   9.266
190   191  Sabah Al Subaiei         Kuwait  1.7  7.200 -4.0   4.900
191   192      Ali Al Jafar         Kuwait  1.7  6.433 -4.0   4.133

[192 rows x 7 columns]

In [4]:
pbq

     Rank           Athlete         Nation    D      E   ND   Total
0       1      Lukas Dauser        Germany  6.3  8.733  NaN  15.033
1       2    Petro Pakhniuk        Ukraine  6.5  8.533  NaN  15.033
2       3        Joe Fraser  Great Britain  6.6  8.400  NaN  15.000
3       4      Xiao Ruoteng          China  6.2  8.766  NaN  14.966
4       5     Ferhat Arican         Turkey  6.5  8.433  NaN  14.933
..    ...               ...            ...  ...    ...  ...     ...
187   188   Manuel Martinez       Colombia  5.2  5.133 -0.3  10.033
188   189   Yerbol Jantykov     Kazakhstan  4.6  4.966  NaN   9.566
189   190     Nabil Zouhair        Morocco  3.0  6.266  NaN   9.266
190   191  Sabah Al Subaiei         Kuwait  1.7  7.200 -4.0   4.900
191   192      Ali Al Jafar         Kuwait  1.7  6.433 -4.0   4.133

[192 rows x 7 columns]

In [5]:
country_to_noc = {
    'Afghanistan': 'AFG',
    'Netherlands Antilles': 'AHO',
    'Albania': 'ALB',
    'Algeria': 'ALG',
    'Andorra': 'AND',
    'Angola': 'ANG',
    'Antigua & Barbuda': 'ANT',
    'Argentina': 'ARG',
    'Armenia': 'ARM',
    'Aruba': 'ARU',
    'American Samoa': 'ASA',
    'Australia': 'AUS',
    'Austria': 'AUT',
    'Azerbaijan': 'AZE',
    'Bahamas': 'BAH',
    'Bangladesh': 'BAN',
    'Barbados': 'BAR',
    'Burundi': 'BDI',
    'Belgium': 'BEL',
    'Benin': 'BEN',
    'Bermuda': 'BER',
    'Bhutan': 'BHU',
    'Bosnia-Herzegovina': 'BIH',
    'Belize': 'BIZ',
    'Belarus': 'BLR',
    'Bolivia': 'BOL',
    'Botswana': 'BOT',
    'Brazil': 'BRA',
    'Bahrain': 'BRN',
    'Brunei': 'BRU',
    'Bulgaria': 'BUL',
    'Burkina Faso': 'BUR',
    'Central African Republic': 'CAF',
    'Cambodia': 'CAM',
    'Canada': 'CAN',
    'Cayman Islands': 'CAY',
    'Republic of the Congo': 'CGO',
    'Chad': 'CHA',
    'Chile': 'CHI',
    'China': 'CHN',  # Add China
    'Ivory Coast (CÃ´te dÂ´Ivoire)': 'CIV',
    'Cameroon': 'CMR',
    'Democratic Republic of the Congo': 'COD',
    'Cook Islands': 'COK',
    'Colombia': 'COL',
    'Comoros': 'COM',
    'Cape Verde': 'CPV',
    'Costa Rica': 'CRC',
    'Croatia': 'CRO',
    'Cuba': 'CUB',
    'Cyprus': 'CYP',
    'Czech Republic': 'CZE',
    'Denmark': 'DEN',
    'Djibouti': 'DJI',
    'Dominica': 'DMA',
    'Dominican Republic': 'DOM',
    'Ecuador': 'ECU',
    'Egypt': 'EGY',
    'England': 'ENG',
    'Eritrea': 'ERI',
    'El Salvador': 'ESA',
    'Spain': 'ESP',
    'Estonia': 'EST',
    'Ethiopia': 'ETH',
    'Fiji': 'FIJ',
    'Finland': 'FIN',
    'France': 'FRA',
    'Federal Republic of Germany': 'FRG',
    'Micronesia': 'FSM',
    'Gabon': 'GAB',
    'The Gambia': 'GAM',
    'United Kingdom of Great Britain & Northern Ireland': 'GBR',
    'Guinea-Bissau': 'GBS',
    'German Democratic Republic': 'GDR',
    'Georgia': 'GEO',
    'Equatorial Guinea': 'GEQ',
    'Germany (previous to 1948 and from 1991)': 'GER',
    'Ghana': 'GHA',
    'Greece': 'GRE',
    'Grenada': 'GRN',
    'Guatemala': 'GUA',
    'Guinea': 'GUI',
    'Guam': 'GUM',
    'Guyana': 'GUY',
    'Haiti': 'HAI',
    'Hong Kong': 'HKG',
    'Honduras': 'HON',
    'Hungary': 'HUN',
    'Indonesia': 'INA',
    'India': 'IND',
    'Iran': 'IRI',
    'Ireland': 'IRL',
    'Iraq': 'IRQ',
    'Iceland': 'ISL',
    'Israel': 'ISR',
    'US Virgin Islands': 'ISV',
    'Italy': 'ITA',
    'British Virgin Islands': 'IVB',
    'Jamaica': 'JAM',
    'Jordan': 'JOR',
    'Japan': 'JPN',
    'Kazakhstan': 'KAZ',
    'Kenya': 'KEN',
    'Kyrgyzstan': 'KGZ',
    'Kiribati': 'KIR',
    'South Korea': 'KOR',
    'Saudi Arabia': 'KSA',
    'Kuwait': 'KUW',
    'Laos': 'LAO',
    'Latvia': 'LAT',
    'Libya': 'LBA',
    'Liberia': 'LBR',
    'Saint Lucia': 'LCA',
    'Lesotho': 'LES',
    'Lebanon': 'LIB',
    'Liechtenstein': 'LIE',
    'Lithuania': 'LTU',
    'Luxembourg': 'LUX',
    'Madagascar': 'MAD',
    'Morocco': 'MAR',
    'Malaysia': 'MAS',
    'Malawi': 'MAW',
    'Moldova': 'MDA',
    'Maldives': 'MDV',
    'Mexico': 'MEX',
    'Mongolia': 'MGL',
    'Marshall Islands': 'MHL',
    'Macedonia': 'MKD',
    'Mali': 'MLI',
    'Malta': 'MLT',
    'Montenegro': 'MNE',
    'Moldova': 'MOL',
    'Monaco': 'MON',
    'Mozambique': 'MOZ',
    'Mauritius': 'MAU',
    'Mauritania': 'MTN',
    'Myanmar': 'MYA',
    'Namibia': 'NAM',
    'Nicaragua': 'NCA',
    'Netherlands': 'NED',
    'Nepal': 'NEP',
    'Nigeria': 'NGR',
    'Northern Ireland': 'NI',
    'Niger': 'NIG',
    'Norway': 'NOR',
    'Northern Rhodesia': 'NRD',
    'Nauru': 'NRU',
    'New Zealand': 'NZL',
    'Oman': 'OMA',
    'Pakistan': 'PAK',
    'Panama': 'PAN',
    'Paraguay': 'PAR',
    'Peru': 'PER',
    'Philippines': 'PHI',
    'Palestine': 'PLE',
    'Palau': 'PLW',
    'Papua New Guinea': 'PNG',
    'Poland': 'POL',
    'Portugal': 'POR',
    'North Korea (Korean PDR)': 'PRK',
    'Puerto Rico': 'PUR',
    'Qatar': 'QAT',
    'Romania': 'ROU',
    'South Africa': 'RSA',
    'Russia': 'RUS',
    'Rwanda': 'RWA',
    'Samoa': 'SAM',
    'Saudi Arabia': 'SAU',
    'Serbia and Montenegro': 'SCG',
    'Scotland': 'Sco',
    'Senegal': 'SEN',
    'Seychelles': 'SEY',
    'Singapore': 'SIN',
    'Saint Kitts and Nevis': 'SKN',
    'South Korea': 'SKR',
    'Sierra Leone': 'SLE',
    'Slovenia': 'SLO',
    'San Marino Republic': 'SMR',
    'Solomon Islands': 'SOL',
    'Somalia': 'SOM',
    'Serbia': 'SRB',
    'Southern Rhodesia': 'SRD',
    'Sri Lanka': 'SRI',
    'SÃ£o Tome and Principe': 'STP',
    'Sudan': 'SUD',
    'Switzerland': 'SUI',
    'Suriname': 'SUR',
    'Slovakia': 'SVK',
    'Sweden': 'SWE',
    'Swaziland': 'SWZ',
    'Syria': 'SYR',
    'Tanzania': 'TAN',
    'Czechoslovakia': 'TCH',
    'Tonga': 'TGA',
    'Thailand': 'THA',
    'Tajikistan': 'TJK',
    'Turkmenistan': 'TKM',
    'Timor-Leste': 'TLS',
    'Togo': 'TOG',
    'Taiwan (Chinese Taipei)': 'TPE',
    'Trinidad & Tobago': 'TRI',
    'Tunisia': 'TUN',
    'Turkey': 'TUR',
    'Tuvalu': 'TUV',
    'United Arab Emirates': 'UAE',
    'Uganda': 'UGA',
    'Ukraine': 'UKR',
    'Unified Team': 'UNT',
    'Soviet Union': 'URS',
    'Uruguay': 'URU',
    'United States': 'USA',
    'Uzbekistan': 'UZB',
    'Vanuatu': 'VAN',
    'Venezuela': 'VEN',
    'Vietnam': 'VIE',
    'St. Vincent and the Grenadines': 'VIN',
    'Wales': 'Wal',
    'West Indies': 'WI',
    'Yemen': 'YEM',
    'Former Yugoslavia': 'yug',
    'Former Yugoslavia': 'yug',
    'Zaire': 'ZAI',
    'Zambia': 'ZAM',
    'Zimbabwe': 'ZIM'
}

In [6]:
fx['round']='final'
hb['round']='final'
pb['round']='final'
sr['round']='final'
ph['round']='final'
iaa['round']='final'

fxq['round']='qual'
hbq['round']='qual'
pbq['round']='qual'
srq['round']='qual'
phq['round']='qual'
iaaq['round']='qual'

In [7]:
combined_df = pd.concat([fx, fxq], ignore_index=True)
fx=combined_df.copy()

combined_df = pd.concat([ph, phq], ignore_index=True)
ph=combined_df.copy()

combined_df = pd.concat([pb, pbq], ignore_index=True)
pb=combined_df.copy()

combined_df = pd.concat([sr, srq], ignore_index=True)
sr=combined_df.copy()

combined_df = pd.concat([hb, hbq], ignore_index=True)
hb=combined_df.copy()

combined_df = pd.concat([iaa, iaaq], ignore_index=True)
iaa=combined_df.copy()

In [8]:
fx['year']=2019
hb['year']=2019
pb['year']=2019
sr['year']=2019
ph['year']=2019
iaa['year']=2019

In [9]:
fx['Athlete'] = fx['Athlete'].str.lower()
pb['Athlete'] = pb['Athlete'].str.lower()
ph['Athlete'] = ph['Athlete'].str.lower()
sr['Athlete'] = sr['Athlete'].str.lower()
hb['Athlete'] = hb['Athlete'].str.lower()
iaa['Athlete'] = iaa['Athlete'].str.lower()

In [10]:
fx['ND'].fillna(0, inplace=True)
pb['ND'].fillna(0, inplace=True)
ph['ND'].fillna(0, inplace=True)
sr['ND'].fillna(0, inplace=True)
hb['ND'].fillna(0, inplace=True)

In [11]:
hb['Nation'] = hb['Nation'].map(country_to_noc)
pb['Nation'] = pb['Nation'].map(country_to_noc)
sr['Nation'] = sr['Nation'].map(country_to_noc)
ph['Nation'] = ph['Nation'].map(country_to_noc)
fx['Nation'] = fx['Nation'].map(country_to_noc)
iaa['Nation'] = iaa['Nation'].map(country_to_noc)

In [12]:
fx['Nation'].fillna('none', inplace=True)
pb['Nation'].fillna('none', inplace=True)
ph['Nation'].fillna('none', inplace=True)
sr['Nation'].fillna('none', inplace=True)
hb['Nation'].fillna('none', inplace=True)
iaa['Nation'].fillna('none', inplace=True)

In [13]:
# fx.to_csv('world19cup_fx.csv', index=False)
# pb.to_csv('world19cup_pb.csv', index=False)
# ph.to_csv('world19cup_ph.csv', index=False)
# sr.to_csv('world19cup_sr.csv', index=False)
# hb.to_csv('world19cup_hb.csv', index=False)
# iaa.to_csv('world19cup_iaa.csv', index=False)

In [14]:
iaa

,Rank,Athlete,Nation,FX,PH,SR,VT,PB,HB,AA,round,year
0,1,nikita nagornyy,RUS,15.041,14.566,14.633,15.066,15.3,14.166,88.772,final,2019
1,2,artur dalaloyan,RUS,15.2,14.0,14.433,14.066,15.233,14.233,87.165,final,2019
2,3,oleg verniaiev,UKR,14.166,14.866,14.0,14.8,15.475,13.666,86.973,final,2019
3,4,xiao ruoteng,CHN,15.025,15.0,13.933,14.8,15.266,12.666,86.690,final,2019
4,5,sun wei,CHN,14.033,14.991,13.966,14.6,14.933,14.0,86.523,final,2019
...,...,...,...,...,...,...,...,...,...,...,...,...
277,â€”,saso bertoncelj,SLO,â€”â€”,12.033,â€”â€”,â€”â€”,â€”â€”,â€”â€”,12.033,qual,2019
278,â€”,saeedreza keikha,IRI,â€”â€”,11.883,â€”â€”,â€”â€”,â€”â€”,â€”â€”,11.883,qual,2019
279,â€”,robert seligman,CRO,â€”â€”,11.333,â€”â€”,â€”â€”,â€”â€”,â€”â€”,11.333,qual,2019
280,â€”,yazan al souliman,SYR,11,â€”â€”,â€”â€”,â€”â€”,â€”â€”,â€”â€”,11.000,qual,2019
281,â€”,ahmad abu al soud,JOR,â€”â€”,10.5,â€”â€”,â€”â€”,â€”â€”,â€”â€”,10.500,qual,2019