In [1]:
import pandas as pd
import numpy as np

In [2]:
pac16bb = pd.read_csv('../Cleaning/qual_events/clean_pacific_rim2016bb.csv')
bc15bb = pd.read_csv('../Cleaning/qual_events/clean_british_championship2015bb.csv')
jesolo15bb = pd.read_csv('../Cleaning/qual_events/clean_jesolo2015bb.csv')
wc13cott_bb = pd.read_csv('../Cleaning/qual_events/clean_wc13cott_bb.csv')
wc13doha_bb = pd.read_csv('../Cleaning/qual_events/clean_wc14doha_bb.csv')
wc19doha_bb = pd.read_csv('../Cleaning/qual_events/clean_worldcup2019doha_bb.csv')
eu20_bb = pd.read_csv('../Cleaning/qual_events/euro2020bb.csv')
uni19_bb = pd.read_csv('../Cleaning/qual_events/uni2019bb.csv')
wc19melb_bb = pd.read_csv('../Cleaning/qual_events/clean_worldcup2019melbourne_bb.csv')
wc18jeso_bb = pd.read_csv('../Cleaning/qual_events/clean_worldcup2018jesolo_bb.csv')
usopc_bb = pd.read_csv('../Cleaning/USOPC/usopc_women_bb_october.csv')
bb_world_championship_w = pd.read_csv('../Cleaning/World_Championships/bb_world_championship_w.csv')
# wc15cott_bb = pd.read_csv('../Cleaning/qual_events/clean_worldcup2015cott_bb.csv')
bb_euro_championship18 = pd.read_csv('../Cleaning/qual_events/clean_european_championship2018bb.csv')
bb_euro_championship21 = pd.read_csv('../Cleaning/qual_events/clean_european_championship2021bb.csv')
pam14am_bb = pd.read_csv('../Cleaning/qual_events/clean_pan_american2014bb.csv')
euro19games_bb= pd.read_csv('../Cleaning/qual_events/clean_european_games2019bb.csv')

clean_universiade2015bb= pd.read_csv('../Cleaning/qual_events/clean_universiade2015bb.csv')
clean_euro15champ_bb= pd.read_csv('../Cleaning/qual_events/clean_euro15champ_bb.csv')

In [3]:
eu20_bb.rename(columns={'Gymnast': 'Name', 'Position': 'Rank', 'Penalty': 'Pen.'}, inplace=True)
uni19_bb['nation'] = uni19_bb['Athlete'].str.extract(r'\((.*?)\)')
uni19_bb['Athlete'] = uni19_bb['Athlete'].str.replace(r'\(.*?\)', '', regex=True)
uni19_bb['year']=2019
eu20_bb['year']=2020
eu20_bb['nation']='eu'
uni19_bb.rename(columns={'Athlete': 'Name', }, inplace=True)
uni19_bb['round']='final'
eu20_bb['round']='final'

In [4]:
def rename_columns(dataframe):
    # Define the column name mapping
    column_name_mapping = {
        'Athlete': 'Name',
        'Gymnast': 'Name',
        'Nation': 'nation',
        'D': 'D Score',
        'E': 'E Score',
        'ND': 'Pen.',
        'Score': 'Total',
        'Position': 'Rank'
        # Add more columns as needed
    }

    return dataframe.rename(columns=column_name_mapping, inplace=True)

In [5]:
rename_columns(wc19melb_bb)

In [6]:
def reorder_columns(dataframe):
    # Define the desired column order
    desired_column_order = ['Rank', 'Name', 'nation', 'D Score', 'E Score', 'Pen.', 'Total', 'year', 'round']

    return dataframe[desired_column_order]

In [7]:
wc19melb_bb = reorder_columns(wc19melb_bb)

Functions

    rename_columns(wc19melb_ub)

    wc19melb_ub = reorder_columns(wc19melb_ub)

In [8]:
rename_columns(pac16bb)

In [9]:
pac16bb = reorder_columns(pac16bb)

In [10]:
rename_columns(bc15bb)

In [11]:
bc15bb = reorder_columns(bc15bb)

In [12]:
rename_columns(jesolo15bb)

In [13]:
jesolo15bb = reorder_columns(jesolo15bb)

In [14]:
rename_columns(wc13cott_bb)

In [15]:
wc13cott_bb = reorder_columns(wc13cott_bb)

In [16]:
rename_columns(wc13doha_bb)

In [17]:
wc13doha_bb = reorder_columns(wc13doha_bb)

In [18]:
rename_columns(wc19doha_bb)

In [19]:
# Create a dictionary to specify the column name changes
column_name_mapping = {
    'Round': 'round'
}

# Use the rename method to rename the columns
wc19doha_bb.rename(columns=column_name_mapping, inplace=True)

In [20]:
wc19doha_bb = reorder_columns(wc19doha_bb)

In [21]:
rename_columns(eu20_bb)

In [22]:
wc13doha_bb = reorder_columns(eu20_bb)

In [23]:
rename_columns(uni19_bb)

In [24]:
uni19_bb = reorder_columns(uni19_bb)

In [25]:
rename_columns(wc18jeso_bb)

In [26]:
wc18jeso_bb['year']=2018
wc18jeso_bb['round']='final'

In [27]:
wc18jeso_bb = reorder_columns(wc18jeso_bb)

In [28]:
rename_columns(bb_world_championship_w)

In [29]:
bb_world_championship_w = reorder_columns(bb_world_championship_w)

In [30]:
bb_world_championship_w

,Rank,Name,nation,D Score,E Score,Pen.,Total,year,round
0,1,Sui Lu,CHN,6.6,9.266,0.0,15.866,2011,final
1,2,Yao Jinnan,CHN,6.3,8.933,0.0,15.233,2011,final
2,3,Jordyn Wieber,USA,6.2,8.933,0.0,15.133,2011,final
3,4,Aly Raisman,USA,6.4,8.666,0.0,15.066,2011,final
4,5,Amelia Racea,ROU,5.9,8.633,0.0,14.533,2011,final
5,6,Yulia Inshina,RUS,5.7,8.825,0.0,14.525,2011,final
6,7,Cătălina Ponor,ROU,5.7,8.541,0.0,14.241,2011,final
7,8,Viktoria Komova,RUS,5.9,7.866,0.0,13.766,2011,final
8,1,Aliya Mustafina,RUS,6.0,8.900,0.0,14.900,2013,final
9,2,Kyla Ross,USA,6.0,8.833,0.0,14.833,2013,final
10,3,Simone Biles,USA,6.1,8.233,0.0,14.333,2013,final
11,4,Vanessa Ferrari,ITA,5.7,8.600,0.0,14.300,2013,final
12,5,Carlotta Ferlito,ITA,5.9,8.383,0.0,14.283,2013,final
13,6,Shang Chunsong,CHN,6.2,7.933,0.0,14.133,2013,final
14,7,Larisa Iordache,ROU,6.3,7.633,0.0,13.933,2013,final
15,8,Anna Rodionova,RUS,5.7,7.400,0.0,13.100,2013,final
16,1,Simone Biles,USA,6.4,8.700,0.0,15.100,2014,final
17,2,Bai Yawen,CHN,6.2,8.833,0.0,15.033,2014,final
18,3,Aliya Mustafina,RUS,5.5,8.666,0.0,14.166,2014,final
19,4,Asuka Teramoto,JPN,5.6,8.500,0.0,14.100,2014,final
20,5,Larisa Iordache,ROU,6.2,7.866,0.0,14.066,2014,final
21,6,Kyla Ross,USA,5.6,8.266,0.0,13.866,2014,final
22,7,Elsabeth Black,CAN,6.3,7.400,0.0,13.700,2014,final
23,8,Yao Jinnan,CHN,5.7,7.666,0.0,13.366,2014,final
24,1,Simone Biles,USA,6.4,8.958,0.0,15.358,2015,final
25,2,Sanne Wevers,NED,5.7,8.633,0.0,14.333,2015,final
26,3,Pauline Schäfer,GER,5.8,8.333,0.0,14.133,2015,final
27,4,Viktoria Komova,RUS,5.7,8.233,0.0,13.933,2015,final
28,5,Wang Yan,CHN,6.4,7.233,0.0,13.633,2015,final
29,6,Seda Tutkhalyan,RUS,6.0,7.500,0.0,13.500,2015,final
30,7,Ellie Black,CAN,6.0,7.466,0.0,13.466,2015,final
31,8,Eythora Thorsdottir,NED,5.7,7.033,0.0,12.733,2015,final
32,1,Pauline Schäfer,NaN,5.5,8.033,0.0,13.533,2017,final
33,2,Morgan Hurd,NaN,5.7,7.800,-0.1,13.400,2017,final
34,3,Tabea Alt,NaN,5.7,7.600,0.0,13.300,2017,final
35,4,Mai Murakami,NaN,5.4,7.666,0.0,13.066,2017,final
36,5,Elena Eremina,NaN,5.4,7.566,0.0,12.966,2017,final
37,6,Asuka Teramoto,NaN,5.6,7.366,0.0,12.966,2017,final
38,7,Liu Tingting,NaN,5.5,7.366,-0.1,12.766,2017,final
39,8,Ellie Black,NaN,5.7,6.700,0.0,12.400,2017,final
40,1,Liu Tingting,NaN,6.3,8.233,0.0,14.533,2018,final
41,2,Ana Padurariu,NaN,6.0,8.100,0.0,14.100,2018,final
42,3,Simone Biles,NaN,6.2,7.400,0.0,13.600,2018,final
43,4,Nina Derwael,NaN,5.4,8.066,0.0,13.466,2018,final
44,5,Ellie Black,NaN,4.8,8.233,0.0,13.033,2018,final
45,6,Kara Eaker,NaN,6.2,6.733,0.1,12.833,2018,final
46,7,Sanne Wevers,NaN,5.3,7.366,0.0,12.666,2018,final
47,8,Zhang Jin,NaN,5.3,6.200,0.0,11.500,2018,final
48,1,Simone Biles,NaN,6.4,8.666,0.0,15.066,2019,final
49,2,Liu Tingting,NaN,6.2,8.233,0.0,14.433,2019,final
50,3,Li Shijia,NaN,6.1,8.300,0.1,14.300,2019,final
51,4,Kara Eaker,NaN,5.9,8.100,0.0,14.000,2019,final
52,5,Mélanie de Jesus dos Santos,NaN,5.5,8.466,0.0,13.966,2019,final
53,6,Flávia Saraiva,NaN,5.7,7.700,0.0,13.400,2019,final
54,7,Sarah Voss,NaN,5.4,7.866,0.0,13.266,2019,final
55,8,Ana Padurariu,NaN,5.6,6.333,0.0,11.933,2019,final

In [31]:
usopc_bb=usopc_bb.drop(columns=["Gender", 'Competition', 'Apparatus', ])
usopc_bb['year'] = usopc_bb['Date'].str[:4]
usopc_bb=usopc_bb.drop(columns=["Date"])

In [32]:
usopc_bb.rename(columns={'Country': 'nation', 'Round': 'round',
                           'E_Score': 'E Score','D_Score': 'D Score', 'Penalty': 'Pen.',
                        'Score': 'Total'}, inplace=True)

usopc_bb=usopc_bb[['Rank', 'Name', 'nation', 'D Score', 'E Score', 'Pen.', 
                         'Total','year' , 'round' ]]

In [33]:
combined_df = pd.concat([wc19melb_bb, pac16bb,bc15bb,jesolo15bb, wc13cott_bb, wc13doha_bb])

In [34]:
bb = combined_df.copy()

In [35]:
bb.info()

<class 'pandas.core.frame.DataFrame'>
Index: 94 entries, 0 to 7
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     94 non-null     int64
 1   Name     94 non-null     object
 2   nation   94 non-null     object
 3   D Score  94 non-null     float64
 4   E Score  94 non-null     float64
 5   Pen.     94 non-null     float64
 6   Total    94 non-null     float64
 7   year     94 non-null     int64
 8   round    94 non-null     object
dtypes: float64(4), int64(2), object(3)
memory usage: 7.3+ KB

In [36]:
combined_df = pd.concat([bb, wc19doha_bb, eu20_bb, uni19_bb, wc18jeso_bb, 
                         bb_world_championship_w, usopc_bb])

In [37]:
bb = combined_df.copy()

In [38]:
bb.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1554 entries, 0 to 1340
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     1554 non-null   float64
 1   Name     1554 non-null   object
 2   nation   1515 non-null   object
 3   D Score  1554 non-null   float64
 4   E Score  1554 non-null   float64
 5   Pen.     1546 non-null   float64
 6   Total    1554 non-null   float64
 7   year     1554 non-null   object
 8   round    1554 non-null   object
dtypes: float64(5), object(4)
memory usage: 121.4+ KB

In [39]:
bb.head(1)

   Rank          Name nation  D Score  E Score  Pen.   Total  year  round
0   1.0  Zhao Shiting    CHN      5.0    8.566   0.0  13.566  2019  final

In [40]:
bb_euro_championship18.head()

,Rank,Athlete,Nation,D,E,ND,Total,year,round
0,1,Mélanie De Jesus Dos Santos,FRA,6.0,7.900,0.0,13.900,2021,final
1,2,Sanne Wevers,NED,5.6,8.266,0.0,13.866,2021,final
2,3,Anastasiia Bachynska,UKR,5.6,7.733,0.0,13.333,2021,final
3,4,Amelie Morgan,GBR,5.3,7.866,0.0,13.166,2021,final
4,5,Martina Maggio,ITA,4.9,8.100,0.0,13.000,2021,final

In [41]:
bb_euro_championship21.head()

,Rank,Athlete,Nation,D,E,ND,Total,year,round
0,1,Sanne Wevers,NED,5.6,8.300,0.0,13.900,2021,final
1,2,Nina Derwael,BEL,5.0,8.600,0.0,13.600,2021,final
2,3,Marine Boyer,FRA,5.8,7.366,0.0,13.166,2021,final
3,4,Melanie De Jesus Dos Santos,FRA,5.4,7.666,0.0,13.066,2021,final
4,5,Ilaria Käslin,SUI,5.1,7.466,-0.1,12.466,2021,final

In [42]:
rename_columns(bb_euro_championship18)

In [43]:
rename_columns(bb_euro_championship21)

In [44]:
combined_df = pd.concat([bb, bb_euro_championship18, bb_euro_championship21])

In [45]:
bb = combined_df.copy()

In [46]:
bb

    Rank              Name nation  D Score  E Score  Pen.   Total  year  round
0    1.0      Zhao Shiting    CHN      5.0    8.566   0.0  13.566  2019  final
1    2.0        Emma Nedov    AUS      5.4    8.100   0.0  13.500  2019  final
2    3.0       Mana Oguchi    JPN      5.1    7.966   0.0  13.066  2019  final
3    4.0  Elena Chipizubov    AUS      5.1    7.933   0.0  13.033  2019  final
4    5.0        Lai Pin-Ju    TPE      5.1    7.333   0.0  12.433  2019  final
..   ...               ...    ...      ...      ...   ...     ...   ...    ...
90  83.0    Greta Banishka    BUL      4.1    4.700   NaN   8.800  2021   qual
91  84.0      Thea Nygaard    NOR      4.7    4.100   NaN   8.800  2021   qual
92  85.0     Victoria Kajø    DEN      4.3    4.000   NaN   8.300  2021   qual
93  86.0  Linda Tugarinova    LAT      3.7    4.533   NaN   8.233  2021   qual
94  87.0  Marina Nekrasova    AZE      1.6    7.666  -6.5   2.766  2021   qual

[1757 rows x 9 columns]

In [47]:
bb.duplicated().sum()

15

In [48]:
bb = bb.drop_duplicates()

In [49]:
# pam14am_bb 
# euro19games_bb

In [50]:
rename_columns(pam14am_bb)
pam14am_bb = reorder_columns(pam14am_bb)

In [51]:
rename_columns(euro19games_bb)
euro19games_bb = reorder_columns(euro19games_bb)

In [52]:
combined_df = pd.concat([bb, pam14am_bb, euro19games_bb])

In [53]:
bb = combined_df.copy()

In [54]:
bb.duplicated().sum()

0

In [59]:
rename_columns(clean_universiade2015bb)
clean_universiade2015bb = reorder_columns(clean_universiade2015bb)

In [62]:
rename_columns(clean_euro15champ_bb)
clean_euro15champ_bb = reorder_columns(clean_euro15champ_bb)

In [65]:
combined_df = pd.concat([bb, clean_universiade2015bb, clean_euro15champ_bb])

In [66]:
bb = combined_df.copy()

In [67]:
bb.duplicated().sum()

0

In [70]:
# bb.to_csv('bb_w.csv', index=False)