In [8]:
import pandas as pd 
import numpy as np

In [11]:
bb = pd.read_csv('../../../scraping/women/eurochamp2021/euro2021champ_bb.csv')
ub = pd.read_csv('../../../scraping/women/eurochamp2021/euro2021champ_ub.csv')
vt = pd.read_csv('../../../scraping/women/eurochamp2021/euro2021champ_vt.csv')
fx = pd.read_csv('../../../scraping/women/eurochamp2021/euro2021champ_fx.csv')

bbq = pd.read_csv('../../../scraping/women/eurochamp2021/euro2021champ_bb_qual.csv')
ubq = pd.read_csv('../../../scraping/women/eurochamp2021/euro2021champ_ub_qual.csv')
fxq = pd.read_csv('../../../scraping/women/eurochamp2021/euro2021champ_fx_qual.csv')

In [3]:
bb['year']=2021
ub['year']=2021
fx['year']=2021
vt['year']=2021

bbq['year']=2021
ubq['year']=2021
fxq['year']=2021

In [4]:
bb['ND'].fillna(0, inplace=True)
vt['ND'].fillna(0, inplace=True)
ub['ND'].fillna(0, inplace=True)
fx['ND'].fillna(0, inplace=True)

In [5]:
bb['round']='final'
ub['round']='final'
fx['round']='final'
vt['round']='final'

bbq['round']='qual'
ubq['round']='qual'
fxq['round']='qual'

In [6]:
bb

,Rank,Athlete,Nation,D,E,ND,Total,year,round
0,1,Mélanie De Jesus Dos Santos,France,6.0,7.900,0.0,13.900,2021,final
1,2,Sanne Wevers,Netherlands,5.6,8.266,0.0,13.866,2021,final
2,3,Anastasiia Bachynska,Ukraine,5.6,7.733,0.0,13.333,2021,final
3,4,Amelie Morgan,Great Britain,5.3,7.866,0.0,13.166,2021,final
4,5,Martina Maggio,Italy,4.9,8.100,0.0,13.000,2021,final
5,6,Marine Boyer,France,5.3,7.566,0.0,12.866,2021,final
6,7,Lieke Wevers,Netherlands,5.1,7.200,0.0,12.300,2021,final
7,8,Elina Vihrova,Latvia,4.6,6.600,0.0,11.200,2021,final

In [7]:
bbq

,Rank,Athlete,Nation,D,E,ND,Total,year,round
0,1,Larisa Iordache,Romania,6.1,7.366,NaN,13.466,2021,qual
1,2,Sanne Wevers,Netherlands,5.3,8.133,NaN,13.433,2021,qual
2,3,Amelie Morgan,Great Britain,5.4,8.033,NaN,13.433,2021,qual
3,4,Lieke Wevers,Netherlands,5.2,8.200,NaN,13.400,2021,qual
4,5,Martina Maggio,Italy,5.2,8.166,NaN,13.366,2021,qual
...,...,...,...,...,...,...,...,...,...
95,96,Edel Fosse,Norway,4.1,4.866,NaN,8.966,2021,qual
96,97,Arina Olenova,Latvia,4.5,4.466,NaN,8.966,2021,qual
97,98,Elvira Katsali,Greece,4.9,4.366,-0.4,8.866,2021,qual
98,99,Milana Minakovskaya,Azerbaijan,4.7,4.108,-0.1,8.708,2021,qual
99,100,Marija Ribalcenko,Latvia,4.7,4.066,-0.1,8.666,2021,qual

In [8]:
combined_df = pd.concat([ub, ubq], axis=0)

In [9]:
ub = combined_df.copy()

In [10]:
combined_df = pd.concat([fx, fxq], axis=0)

In [11]:
fx = combined_df.copy()

In [12]:
combined_df = pd.concat([bb, bbq], axis=0)

In [13]:
bb = combined_df.copy()

In [14]:
bb['Nation'].unique()

array(['France', 'Netherlands', 'Ukraine', 'Great Britain', 'Italy',
       'Latvia', 'Romania', 'Poland', 'Russia', 'Portugal', 'Sweden',
       'Germany', 'Turkey', 'Finland', 'Hungary', 'Czech Republic',
       'Israel', 'Slovakia', 'Austria', 'Ireland', 'Norway',
       'Switzerland', 'Belgium', 'Iceland', 'Denmark', 'Croatia',
       'Greece', 'Belarus', 'orway', 'Lithuania', 'Azerbaijan',
       'Slovenia', 'Luxembourg'], dtype=object)

In [15]:
country_code_mapping = {
    'France': 'FRA',
    'Netherlands': 'NED',
    'Ukraine': 'UKR',
    'Great Britain': 'GBR',
    'Italy': 'ITA',
    'Latvia': 'LAT',
    'Romania': 'ROU',
    'Poland': 'POL',
    'Russia': 'RUS',
    'Portugal': 'POR',
    'Sweden': 'SWE',
    'Germany': 'GER',
    'Turkey': 'TUR',
    'Finland': 'FIN',
    'Hungary': 'HUN',
    'Czech Republic': 'CZE',
    'Israel': 'ISR',
    'Slovakia': 'SVK',
    'Austria': 'AUT',
    'Ireland': 'IRL',
    'Norway': 'NOR',
    'Switzerland': 'SUI',
    'Belgium': 'BEL',
    'Iceland': 'ISL',
    'Denmark': 'DEN',
    'Croatia': 'CRO',
    'Greece': 'GRE',
    'Belarus': 'BLR',
    'Lithuania': 'LTU',
    'Azerbaijan': 'AZE',
    'Slovenia': 'SLO',
    'Luxembourg': 'LUX'
}

# Map the 'Nation' values to their NOC country codes
bb['Nation'] = bb['Nation'].replace(country_code_mapping)

In [16]:
bb

,Rank,Athlete,Nation,D,E,ND,Total,year,round
0,1,Mélanie De Jesus Dos Santos,FRA,6.0,7.900,0.0,13.900,2021,final
1,2,Sanne Wevers,NED,5.6,8.266,0.0,13.866,2021,final
2,3,Anastasiia Bachynska,UKR,5.6,7.733,0.0,13.333,2021,final
3,4,Amelie Morgan,GBR,5.3,7.866,0.0,13.166,2021,final
4,5,Martina Maggio,ITA,4.9,8.100,0.0,13.000,2021,final
...,...,...,...,...,...,...,...,...,...
95,96,Edel Fosse,NOR,4.1,4.866,NaN,8.966,2021,qual
96,97,Arina Olenova,LAT,4.5,4.466,NaN,8.966,2021,qual
97,98,Elvira Katsali,GRE,4.9,4.366,-0.4,8.866,2021,qual
98,99,Milana Minakovskaya,AZE,4.7,4.108,-0.1,8.708,2021,qual
99,100,Marija Ribalcenko,LAT,4.7,4.066,-0.1,8.666,2021,qual

In [17]:
ub['Nation'].unique()

array(['Russia', 'Great Britain', 'Italy', 'Sweden', 'Germany',
       'Portugal', 'Ukraine', 'Belgium', 'Finland', 'Romania', 'Slovakia',
       'Netherlands', 'France', 'Belarus', 'Ireland', 'Switzerland',
       'Latvia', 'Hungary', 'Slovenia', 'Austria', 'Israel', 'Poland',
       'Luxembourg', 'Denmark', 'Czech Republic', 'Turkey', 'Croatia',
       'Iceland', 'Norway', 'Greece', 'Lithuania', 'Azerbaijan'],
      dtype=object)

In [18]:
country_code_mapping = {
    'Russia': 'RUS',
    'Great Britain': 'GBR',
    'Italy': 'ITA',
    'Sweden': 'SWE',
    'Germany': 'GER',
    'Portugal': 'POR',
    'Ukraine': 'UKR',
    'Belgium': 'BEL',
    'Finland': 'FIN',
    'Romania': 'ROU',
    'Slovakia': 'SVK',
    'Netherlands': 'NED',
    'France': 'FRA',
    'Belarus': 'BLR',
    'Ireland': 'IRL',
    'Switzerland': 'SUI',
    'Latvia': 'LAT',
    'Hungary': 'HUN',
    'Slovenia': 'SLO',
    'Austria': 'AUT',
    'Israel': 'ISR',
    'Poland': 'POL',
    'Luxembourg': 'LUX',
    'Denmark': 'DEN',
    'Czech Republic': 'CZE',
    'Turkey': 'TUR',
    'Croatia': 'CRO',
    'Iceland': 'ISL',
    'Norway': 'NOR',
    'Greece': 'GRE',
    'Lithuania': 'LTU',
    'Azerbaijan': 'AZE'
}



# Map the 'Country' values to their NOC country codes
ub['Nation'] = ub['Nation'].replace(country_code_mapping)

In [19]:
fx['Nation'].unique()

array(['Great Britain', 'Russia', 'Italy', 'Romania', 'Germany', 'France',
       'Switzerland', 'Ukraine', 'Belgium', 'Netherlands', 'Croatia',
       'Turkey', 'Austria', 'Hungary', 'Poland', 'Czech Republic',
       'Portugal', 'Finland', 'Israel', 'Latvia', 'Greece', 'Sweden',
       'Slovakia', 'Iceland', 'Norway', 'Denmark', 'Luxembourg',
       'Ireland', 'Slovenia', 'Azerbaijan', 'Lithuania', 'Belarus'],
      dtype=object)

In [20]:
# Dictionary to map country names to NOC country codes
country_code_mapping = {
    'Great Britain': 'GBR',
    'Russia': 'RUS',
    'Italy': 'ITA',
    'Romania': 'ROU',
    'Germany': 'GER',
    'France': 'FRA',
    'Switzerland': 'SUI',
    'Ukraine': 'UKR',
    'Belgium': 'BEL',
    'Netherlands': 'NED',
    'Croatia': 'CRO',
    'Turkey': 'TUR',
    'Austria': 'AUT',
    'Hungary': 'HUN',
    'Poland': 'POL',
    'Czech Republic': 'CZE',
    'Portugal': 'POR',
    'Finland': 'FIN',
    'Israel': 'ISR',
    'Latvia': 'LAT',
    'Greece': 'GRE',
    'Sweden': 'SWE',
    'Slovakia': 'SVK',
    'Iceland': 'ISL',
    'Norway': 'NOR',
    'Denmark': 'DEN',
    'Luxembourg': 'LUX',
    'Ireland': 'IRL',
    'Slovenia': 'SLO',
    'Azerbaijan': 'AZE',
    'Lithuania': 'LTU',
    'Belarus': 'BLR'
}


# Map the 'Country' values to their NOC country codes
fx['Nation'] = fx['Nation'].replace(country_code_mapping)

In [21]:
fx.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99 entries, 0 to 90
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     99 non-null     int64
 1   Athlete  99 non-null     object
 2   Nation   99 non-null     object
 3   D        99 non-null     float64
 4   E        99 non-null     float64
 5   ND       31 non-null     float64
 6   Total    99 non-null     float64
 7   year     99 non-null     int64
 8   round    99 non-null     object
dtypes: float64(4), int64(2), object(3)
memory usage: 7.7+ KB

In [22]:
vt

,Rank,Athlete,Nation,D,E,ND,Total,D2,E2,ND2,Total2,Average,year,round
0,1,Giulia Steingruber,Switzerland,5.8,9.266,0.0,15.066,5.4,9.183,NaN,14.583,14.824,2021,final
1,2,Jessica Gadirova,Great Britain,5.4,9.200,0.0,14.600,5.2,9.133,NaN,14.333,14.466,2021,final
2,3,Angelina Melnikova,Russia,5.4,9.200,0.0,14.600,5.2,9.033,NaN,14.233,14.416,2021,final
3,4,Anastasiia Motak,Ukraine,5.4,8.633,-0.1,13.933,4.8,8.666,NaN,13.466,13.699,2021,final
4,5,Tjasa Kysselef,Slovenia,5.0,8.700,0.0,13.700,4.8,8.833,NaN,13.633,13.666,2021,final
5,6,Csenge Bacskay,Hungary,5.0,8.766,0.0,13.766,4.8,8.733,NaN,13.533,13.649,2021,final
6,7,Marina Nekrasova,Azerbaijan,5.0,7.533,-0.1,12.433,5.2,8.733,NaN,13.933,13.183,2021,final
7,8,Sara Peter,Hungary,5.4,7.566,0.0,12.966,0.0,0.000,NaN,0.000,6.483,2021,final

In [23]:
vt['ND2'].fillna(0,inplace=True)

In [24]:
vt['Nation'].unique()

array(['Switzerland', 'Great Britain', 'Russia', 'Ukraine', 'Slovenia',
       'Hungary', 'Azerbaijan'], dtype=object)

In [25]:
country_code_mapping = {
    'Switzerland': 'SUI',
    'Great Britain': 'GBR',
    'Russia': 'RUS',
    'Ukraine': 'UKR',
    'Slovenia': 'SLO',
    'Hungary': 'HUN',
    'Azerbaijan': 'AZE'
}


# Map the 'Country' values to their NOC country codes
vt['Nation'] = vt['Nation'].replace(country_code_mapping)

In [26]:
vt

,Rank,Athlete,Nation,D,E,ND,Total,D2,E2,ND2,Total2,Average,year,round
0,1,Giulia Steingruber,SUI,5.8,9.266,0.0,15.066,5.4,9.183,0.0,14.583,14.824,2021,final
1,2,Jessica Gadirova,GBR,5.4,9.200,0.0,14.600,5.2,9.133,0.0,14.333,14.466,2021,final
2,3,Angelina Melnikova,RUS,5.4,9.200,0.0,14.600,5.2,9.033,0.0,14.233,14.416,2021,final
3,4,Anastasiia Motak,UKR,5.4,8.633,-0.1,13.933,4.8,8.666,0.0,13.466,13.699,2021,final
4,5,Tjasa Kysselef,SLO,5.0,8.700,0.0,13.700,4.8,8.833,0.0,13.633,13.666,2021,final
5,6,Csenge Bacskay,HUN,5.0,8.766,0.0,13.766,4.8,8.733,0.0,13.533,13.649,2021,final
6,7,Marina Nekrasova,AZE,5.0,7.533,-0.1,12.433,5.2,8.733,0.0,13.933,13.183,2021,final
7,8,Sara Peter,HUN,5.4,7.566,0.0,12.966,0.0,0.000,0.0,0.000,6.483,2021,final

In [27]:
# vt.to_csv('clean_european_championship2018vt.csv', index=False)
# ub.to_csv('clean_european_championship2018ub.csv', index=False)
# bb.to_csv('clean_european_championship2018bb.csv', index=False)
# fx.to_csv('clean_european_championship2018fx.csv', index=False)