In [2]:
import pandas as pd
import numpy as np

In [3]:
bb = pd.read_csv('../../../scraping/women/worldcup19doha/worldcup2019doha_bb.csv')
bbq = pd.read_csv('../../../scraping/women/worldcup19doha/worldcup2019doha_qual_bb.csv')

ub = pd.read_csv('../../../scraping/women/worldcup19doha/worldcup2019doha_ub.csv')
ubq = pd.read_csv('../../../scraping/women/worldcup19doha/worldcup2019doha_qual_ub.csv')

vt = pd.read_csv('../../../scraping/women/worldcup19doha/worldcup2019doha_vt.csv')
# vtq = pd.read_csv('../../scraping/worldcup19doha/worldcup2019doha_qual_vt.csv')

fx = pd.read_csv('../../../scraping/women/worldcup19doha/worldcup2019doha_fx.csv')
fxq = pd.read_csv('../../../scraping/women/worldcup19doha/worldcup2019doha_qual_fx.csv')

In [3]:
bb['Round'] = "Final"

In [4]:
bbq.head()

   Rank          Athlete          Nation    D      E   ND   Total Round
0     1     Nina Derwael         Belgium  5.3  8.266  NaN  13.566  Qual
1     2     Marine Boyer          France  5.7  7.666  NaN  13.366  Qual
2     3            Li Qi           China  5.7  7.700 -0.1  13.300  Qual
3     4  Yumika Nakamura           Japan  5.0  7.900  NaN  12.900  Qual
4     5    Ting Hua-Tien  Chinese Taipei  5.3  7.500  NaN  12.800  Qual

In [5]:
bb

   Rank          Athlete          Nation    D      E  ND   Total  Round
0     1            Li Qi           China  6.0  8.333 NaN  14.333  Final
1     2     Nina Derwael         Belgium  5.2  8.433 NaN  13.633  Final
2     3     Marine Boyer          France  5.7  7.633 NaN  13.333  Final
3     4       Adela Sajn        Slovenia  4.9  7.933 NaN  12.833  Final
4     5   Aneta Holasova  Czech Republic  5.0  7.800 NaN  12.800  Final
5     6    Ting Hua-Tien  Chinese Taipei  5.5  6.900 NaN  12.400  Final
6     7  Yumika Nakamura           Japan  5.0  6.800 NaN  11.800  Final
7     8    Soyoka Hanawa           Japan  5.5  5.966 NaN  11.466  Final

In [6]:
combined_df = pd.concat([bb, bbq], axis=0)

In [7]:
combined_df

    Rank              Athlete          Nation    D      E   ND   Total  Round
0      1                Li Qi           China  6.0  8.333  NaN  14.333  Final
1      2         Nina Derwael         Belgium  5.2  8.433  NaN  13.633  Final
2      3         Marine Boyer          France  5.7  7.633  NaN  13.333  Final
3      4           Adela Sajn        Slovenia  4.9  7.933  NaN  12.833  Final
4      5       Aneta Holasova  Czech Republic  5.0  7.800  NaN  12.800  Final
5      6        Ting Hua-Tien  Chinese Taipei  5.5  6.900  NaN  12.400  Final
6      7      Yumika Nakamura           Japan  5.0  6.800  NaN  11.800  Final
7      8        Soyoka Hanawa           Japan  5.5  5.966  NaN  11.466  Final
0      1         Nina Derwael         Belgium  5.3  8.266  NaN  13.566   Qual
1      2         Marine Boyer          France  5.7  7.666  NaN  13.366   Qual
2      3                Li Qi           China  5.7  7.700 -0.1  13.300   Qual
3      4      Yumika Nakamura           Japan  5.0  7.900  NaN  12.900   Qual
4      5        Ting Hua-Tien  Chinese Taipei  5.3  7.500  NaN  12.800   Qual
5      6           Adela Sajn        Slovenia  4.9  7.866  NaN  12.766   Qual
6      7        Soyoka Hanawa           Japan  5.9  6.800  NaN  12.700   Qual
7      8       Aneta Holasova  Czech Republic  5.1  7.566  NaN  12.666   Qual
8      9  Marta Pihan-Kulesza          Poland  5.2  7.433  NaN  12.633   Qual
9     10       Varvara Zubova          Russia  5.6  6.933  NaN  12.533   Qual
10    11       Diana Varinska         Ukraine  5.3  7.000  NaN  12.300   Qual
11    12       Csenge Bacskay         Hungary  5.0  7.266  NaN  12.266   Qual
12    13           Lai Pin-Ju  Chinese Taipei  5.1  7.166  NaN  12.266   Qual
13    14       Gabriela Janik          Poland  4.6  7.533 -0.1  12.033   Qual
14    15     Coline Devillard          France  5.0  6.833  NaN  11.833   Qual
15    16       Elisa Hämmerle         Austria  4.7  7.100  NaN  11.800   Qual
16    17         Emily Thomas   Great Britain  4.8  6.966  NaN  11.766   Qual
17    18     Phoebe Jakubczyk   Great Britain  4.9  6.800  NaN  11.700   Qual
18    19          An Chang Ok     North Korea  4.9  6.700  NaN  11.600   Qual
19    20        Kim Son Hyang     North Korea  5.3  6.400 -0.1  11.600   Qual
20    21              Kim Bui         Germany  4.9  6.666 -0.1  11.466   Qual
21    22  Ominakhon Khalilova      Uzbekistan  4.5  6.933  NaN  11.433   Qual
22    23       Lucie Jirikova  Czech Republic  4.5  6.666  NaN  11.166   Qual
23    24            Lara Mori           Italy  5.3  5.633  NaN  10.933   Qual
24    25         Zhao Shiting           China  5.5  5.400 -0.1  10.800   Qual
25    26     Marina Nekrasova      Azerbaijan  5.1  5.733 -0.1  10.733   Qual
26    27          Demet Mutlu          Turkey  4.9  5.766  NaN  10.666   Qual
27    28         Tutya Yilmaz          Turkey  4.8  5.700  NaN  10.500   Qual
28    29  Lisa Katharina Hill         Germany  4.2  5.500  NaN   9.700   Qual
29    30         Zoja Szekely         Hungary  5.1  4.566 -0.1   9.566   Qual
30    31            Ana Derek         Croatia  4.4  4.233  NaN   8.633   Qual

In [8]:
bb = combined_df.copy()

In [9]:
bb["ND"].fillna(0,inplace=True)

In [10]:
bb

    Rank              Athlete          Nation    D      E   ND   Total  Round
0      1                Li Qi           China  6.0  8.333  0.0  14.333  Final
1      2         Nina Derwael         Belgium  5.2  8.433  0.0  13.633  Final
2      3         Marine Boyer          France  5.7  7.633  0.0  13.333  Final
3      4           Adela Sajn        Slovenia  4.9  7.933  0.0  12.833  Final
4      5       Aneta Holasova  Czech Republic  5.0  7.800  0.0  12.800  Final
5      6        Ting Hua-Tien  Chinese Taipei  5.5  6.900  0.0  12.400  Final
6      7      Yumika Nakamura           Japan  5.0  6.800  0.0  11.800  Final
7      8        Soyoka Hanawa           Japan  5.5  5.966  0.0  11.466  Final
0      1         Nina Derwael         Belgium  5.3  8.266  0.0  13.566   Qual
1      2         Marine Boyer          France  5.7  7.666  0.0  13.366   Qual
2      3                Li Qi           China  5.7  7.700 -0.1  13.300   Qual
3      4      Yumika Nakamura           Japan  5.0  7.900  0.0  12.900   Qual
4      5        Ting Hua-Tien  Chinese Taipei  5.3  7.500  0.0  12.800   Qual
5      6           Adela Sajn        Slovenia  4.9  7.866  0.0  12.766   Qual
6      7        Soyoka Hanawa           Japan  5.9  6.800  0.0  12.700   Qual
7      8       Aneta Holasova  Czech Republic  5.1  7.566  0.0  12.666   Qual
8      9  Marta Pihan-Kulesza          Poland  5.2  7.433  0.0  12.633   Qual
9     10       Varvara Zubova          Russia  5.6  6.933  0.0  12.533   Qual
10    11       Diana Varinska         Ukraine  5.3  7.000  0.0  12.300   Qual
11    12       Csenge Bacskay         Hungary  5.0  7.266  0.0  12.266   Qual
12    13           Lai Pin-Ju  Chinese Taipei  5.1  7.166  0.0  12.266   Qual
13    14       Gabriela Janik          Poland  4.6  7.533 -0.1  12.033   Qual
14    15     Coline Devillard          France  5.0  6.833  0.0  11.833   Qual
15    16       Elisa Hämmerle         Austria  4.7  7.100  0.0  11.800   Qual
16    17         Emily Thomas   Great Britain  4.8  6.966  0.0  11.766   Qual
17    18     Phoebe Jakubczyk   Great Britain  4.9  6.800  0.0  11.700   Qual
18    19          An Chang Ok     North Korea  4.9  6.700  0.0  11.600   Qual
19    20        Kim Son Hyang     North Korea  5.3  6.400 -0.1  11.600   Qual
20    21              Kim Bui         Germany  4.9  6.666 -0.1  11.466   Qual
21    22  Ominakhon Khalilova      Uzbekistan  4.5  6.933  0.0  11.433   Qual
22    23       Lucie Jirikova  Czech Republic  4.5  6.666  0.0  11.166   Qual
23    24            Lara Mori           Italy  5.3  5.633  0.0  10.933   Qual
24    25         Zhao Shiting           China  5.5  5.400 -0.1  10.800   Qual
25    26     Marina Nekrasova      Azerbaijan  5.1  5.733 -0.1  10.733   Qual
26    27          Demet Mutlu          Turkey  4.9  5.766  0.0  10.666   Qual
27    28         Tutya Yilmaz          Turkey  4.8  5.700  0.0  10.500   Qual
28    29  Lisa Katharina Hill         Germany  4.2  5.500  0.0   9.700   Qual
29    30         Zoja Szekely         Hungary  5.1  4.566 -0.1   9.566   Qual
30    31            Ana Derek         Croatia  4.4  4.233  0.0   8.633   Qual

In [11]:
bb.info()

<class 'pandas.core.frame.DataFrame'>
Index: 39 entries, 0 to 30
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     39 non-null     int64
 1   Athlete  39 non-null     object
 2   Nation   39 non-null     object
 3   D        39 non-null     float64
 4   E        39 non-null     float64
 5   ND       39 non-null     float64
 6   Total    39 non-null     float64
 7   Round    39 non-null     object
dtypes: float64(4), int64(1), object(3)
memory usage: 2.7+ KB

In [12]:
bb["Nation"].unique()

array(['China', 'Belgium', 'France', 'Slovenia', 'Czech Republic',
       'Chinese Taipei', 'Japan', 'Poland', 'Russia', 'Ukraine',
       'Hungary', 'Austria', 'Great Britain', 'North Korea', 'Germany',
       'Uzbekistan', 'Italy', 'Azerbaijan', 'Turkey', 'Croatia'],
      dtype=object)

In [13]:

# Dictionary mapping nation names to NOC codes
nation_to_noc = {
    'China': 'CHN',
    'Belgium': 'BEL',
    'France': 'FRA',
    'Slovenia': 'SLO',
    'Czech Republic': 'CZE',
    'Chinese Taipei': 'TPE',
    'Japan': 'JPN',
    'Poland': 'POL',
    'Russia': 'RUS',
    'Ukraine': 'UKR',
    'Hungary': 'HUN',
    'Austria': 'AUT',
    'Great Britain': 'GBR',
    'North Korea': 'PRK',
    'Germany': 'GER',
    'Uzbekistan': 'UZB',
    'Italy': 'ITA',
    'Azerbaijan': 'AZE',
    'Turkey': 'TUR',
    'Croatia': 'CRO'
}

# Map the "Nations" column to NOC codes
bb['NOC'] = bb['Nation'].map(nation_to_noc)

In [14]:
bb

,Rank,Athlete,Nation,D,E,ND,Total,Round,NOC
0,1,Li Qi,China,6.0,8.333,0.0,14.333,Final,CHN
1,2,Nina Derwael,Belgium,5.2,8.433,0.0,13.633,Final,BEL
2,3,Marine Boyer,France,5.7,7.633,0.0,13.333,Final,FRA
3,4,Adela Sajn,Slovenia,4.9,7.933,0.0,12.833,Final,SLO
4,5,Aneta Holasova,Czech Republic,5.0,7.800,0.0,12.800,Final,CZE
5,6,Ting Hua-Tien,Chinese Taipei,5.5,6.900,0.0,12.400,Final,TPE
6,7,Yumika Nakamura,Japan,5.0,6.800,0.0,11.800,Final,JPN
7,8,Soyoka Hanawa,Japan,5.5,5.966,0.0,11.466,Final,JPN
0,1,Nina Derwael,Belgium,5.3,8.266,0.0,13.566,Qual,BEL
1,2,Marine Boyer,France,5.7,7.666,0.0,13.366,Qual,FRA
2,3,Li Qi,China,5.7,7.700,-0.1,13.300,Qual,CHN
3,4,Yumika Nakamura,Japan,5.0,7.900,0.0,12.900,Qual,JPN
4,5,Ting Hua-Tien,Chinese Taipei,5.3,7.500,0.0,12.800,Qual,TPE
5,6,Adela Sajn,Slovenia,4.9,7.866,0.0,12.766,Qual,SLO
6,7,Soyoka Hanawa,Japan,5.9,6.800,0.0,12.700,Qual,JPN
7,8,Aneta Holasova,Czech Republic,5.1,7.566,0.0,12.666,Qual,CZE
8,9,Marta Pihan-Kulesza,Poland,5.2,7.433,0.0,12.633,Qual,POL
9,10,Varvara Zubova,Russia,5.6,6.933,0.0,12.533,Qual,RUS
10,11,Diana Varinska,Ukraine,5.3,7.000,0.0,12.300,Qual,UKR
11,12,Csenge Bacskay,Hungary,5.0,7.266,0.0,12.266,Qual,HUN
12,13,Lai Pin-Ju,Chinese Taipei,5.1,7.166,0.0,12.266,Qual,TPE
13,14,Gabriela Janik,Poland,4.6,7.533,-0.1,12.033,Qual,POL
14,15,Coline Devillard,France,5.0,6.833,0.0,11.833,Qual,FRA
15,16,Elisa Hämmerle,Austria,4.7,7.100,0.0,11.800,Qual,AUT
16,17,Emily Thomas,Great Britain,4.8,6.966,0.0,11.766,Qual,GBR
17,18,Phoebe Jakubczyk,Great Britain,4.9,6.800,0.0,11.700,Qual,GBR
18,19,An Chang Ok,North Korea,4.9,6.700,0.0,11.600,Qual,PRK
19,20,Kim Son Hyang,North Korea,5.3,6.400,-0.1,11.600,Qual,PRK
20,21,Kim Bui,Germany,4.9,6.666,-0.1,11.466,Qual,GER
21,22,Ominakhon Khalilova,Uzbekistan,4.5,6.933,0.0,11.433,Qual,UZB
22,23,Lucie Jirikova,Czech Republic,4.5,6.666,0.0,11.166,Qual,CZE
23,24,Lara Mori,Italy,5.3,5.633,0.0,10.933,Qual,ITA
24,25,Zhao Shiting,China,5.5,5.400,-0.1,10.800,Qual,CHN
25,26,Marina Nekrasova,Azerbaijan,5.1,5.733,-0.1,10.733,Qual,AZE
26,27,Demet Mutlu,Turkey,4.9,5.766,0.0,10.666,Qual,TUR
27,28,Tutya Yilmaz,Turkey,4.8,5.700,0.0,10.500,Qual,TUR
28,29,Lisa Katharina Hill,Germany,4.2,5.500,0.0,9.700,Qual,GER
29,30,Zoja Szekely,Hungary,5.1,4.566,-0.1,9.566,Qual,HUN
30,31,Ana Derek,Croatia,4.4,4.233,0.0,8.633,Qual,CRO

In [15]:
bb = bb.drop(columns=["Nation"])
bb["Nation"] = bb["NOC"]
bb = bb.drop(columns=["NOC"])

In [16]:
bb['year'] = 2019

In [17]:
bb

    Rank              Athlete    D      E   ND   Total  Round Nation  year
0      1                Li Qi  6.0  8.333  0.0  14.333  Final    CHN  2019
1      2         Nina Derwael  5.2  8.433  0.0  13.633  Final    BEL  2019
2      3         Marine Boyer  5.7  7.633  0.0  13.333  Final    FRA  2019
3      4           Adela Sajn  4.9  7.933  0.0  12.833  Final    SLO  2019
4      5       Aneta Holasova  5.0  7.800  0.0  12.800  Final    CZE  2019
5      6        Ting Hua-Tien  5.5  6.900  0.0  12.400  Final    TPE  2019
6      7      Yumika Nakamura  5.0  6.800  0.0  11.800  Final    JPN  2019
7      8        Soyoka Hanawa  5.5  5.966  0.0  11.466  Final    JPN  2019
0      1         Nina Derwael  5.3  8.266  0.0  13.566   Qual    BEL  2019
1      2         Marine Boyer  5.7  7.666  0.0  13.366   Qual    FRA  2019
2      3                Li Qi  5.7  7.700 -0.1  13.300   Qual    CHN  2019
3      4      Yumika Nakamura  5.0  7.900  0.0  12.900   Qual    JPN  2019
4      5        Ting Hua-Tien  5.3  7.500  0.0  12.800   Qual    TPE  2019
5      6           Adela Sajn  4.9  7.866  0.0  12.766   Qual    SLO  2019
6      7        Soyoka Hanawa  5.9  6.800  0.0  12.700   Qual    JPN  2019
7      8       Aneta Holasova  5.1  7.566  0.0  12.666   Qual    CZE  2019
8      9  Marta Pihan-Kulesza  5.2  7.433  0.0  12.633   Qual    POL  2019
9     10       Varvara Zubova  5.6  6.933  0.0  12.533   Qual    RUS  2019
10    11       Diana Varinska  5.3  7.000  0.0  12.300   Qual    UKR  2019
11    12       Csenge Bacskay  5.0  7.266  0.0  12.266   Qual    HUN  2019
12    13           Lai Pin-Ju  5.1  7.166  0.0  12.266   Qual    TPE  2019
13    14       Gabriela Janik  4.6  7.533 -0.1  12.033   Qual    POL  2019
14    15     Coline Devillard  5.0  6.833  0.0  11.833   Qual    FRA  2019
15    16       Elisa Hämmerle  4.7  7.100  0.0  11.800   Qual    AUT  2019
16    17         Emily Thomas  4.8  6.966  0.0  11.766   Qual    GBR  2019
17    18     Phoebe Jakubczyk  4.9  6.800  0.0  11.700   Qual    GBR  2019
18    19          An Chang Ok  4.9  6.700  0.0  11.600   Qual    PRK  2019
19    20        Kim Son Hyang  5.3  6.400 -0.1  11.600   Qual    PRK  2019
20    21              Kim Bui  4.9  6.666 -0.1  11.466   Qual    GER  2019
21    22  Ominakhon Khalilova  4.5  6.933  0.0  11.433   Qual    UZB  2019
22    23       Lucie Jirikova  4.5  6.666  0.0  11.166   Qual    CZE  2019
23    24            Lara Mori  5.3  5.633  0.0  10.933   Qual    ITA  2019
24    25         Zhao Shiting  5.5  5.400 -0.1  10.800   Qual    CHN  2019
25    26     Marina Nekrasova  5.1  5.733 -0.1  10.733   Qual    AZE  2019
26    27          Demet Mutlu  4.9  5.766  0.0  10.666   Qual    TUR  2019
27    28         Tutya Yilmaz  4.8  5.700  0.0  10.500   Qual    TUR  2019
28    29  Lisa Katharina Hill  4.2  5.500  0.0   9.700   Qual    GER  2019
29    30         Zoja Szekely  5.1  4.566 -0.1   9.566   Qual    HUN  2019
30    31            Ana Derek  4.4  4.233  0.0   8.633   Qual    CRO  2019

In [18]:
ub.head()

   Rank               Athlete   Nation    D      E  ND   Total
0     1          Nina Derwael  Belgium  6.5  8.533 NaN  15.033
1     2             Fan Yilin    China  6.5  8.433 NaN  14.933
2     3  Anastasiia Iliankova   Russia  6.3  8.400 NaN  14.700
3     4        Jonna Adlerteg   Sweden  6.0  8.216 NaN  14.216
4     5               Kim Bui  Germany  6.0  8.000 NaN  14.000

In [19]:
ubq.head()

   Rank               Athlete   Nation    D      E  ND   Total round
0     1          Nina Derwael  Belgium  6.5  8.533 NaN  15.033  Qual
1     2             Fan Yilin    China  6.3  8.600 NaN  14.900  Qual
2     3  Anastasiia Iliankova   Russia  6.3  8.333 NaN  14.633  Qual
3     4        Diana Varinska  Ukraine  5.7  8.266 NaN  13.966  Qual
4     5               Kim Bui  Germany  6.0  7.900 NaN  13.900  Qual

In [20]:
ub["round"] = "Final"

In [21]:
ub['year'] = 2019

In [22]:
ubq["year"]=2019

In [23]:
combined_df = pd.concat([ub, ubq], axis=0)

In [24]:
ub = combined_df.copy()

In [25]:
ub

,Rank,Athlete,Nation,D,E,ND,Total,round,year
0,1,Nina Derwael,Belgium,6.5,8.533,NaN,15.033,Final,2019
1,2,Fan Yilin,China,6.5,8.433,NaN,14.933,Final,2019
2,3,Anastasiia Iliankova,Russia,6.3,8.400,NaN,14.700,Final,2019
3,4,Jonna Adlerteg,Sweden,6.0,8.216,NaN,14.216,Final,2019
4,5,Kim Bui,Germany,6.0,8.000,NaN,14.000,Final,2019
5,6,Martina Rizzelli,Italy,5.1,7.916,NaN,13.016,Final,2019
6,7,Yumika Nakamura,Japan,5.1,7.833,NaN,12.933,Final,2019
7,8,Diana Varinska,Ukraine,5.0,7.400,NaN,12.400,Final,2019
0,1,Nina Derwael,Belgium,6.5,8.533,NaN,15.033,Qual,2019
1,2,Fan Yilin,China,6.3,8.600,NaN,14.900,Qual,2019
2,3,Anastasiia Iliankova,Russia,6.3,8.333,NaN,14.633,Qual,2019
3,4,Diana Varinska,Ukraine,5.7,8.266,NaN,13.966,Qual,2019
4,5,Kim Bui,Germany,6.0,7.900,NaN,13.900,Qual,2019
5,6,Jonna Adlerteg,Sweden,6.0,7.366,NaN,13.366,Qual,2019
6,7,Martina Rizzelli,Italy,5.4,7.833,NaN,13.233,Qual,2019
7,8,Yumika Nakamura,Japan,5.1,8.000,NaN,13.100,Qual,2019
8,9,Lisa Katharina Hill,Germany,5.4,7.433,NaN,12.833,Qual,2019
9,10,Emily Thomas,Great Britain,4.9,7.800,NaN,12.700,Qual,2019
10,11,Zoja Szekely,Hungary,6.0,6.700,NaN,12.700,Qual,2019
11,12,Soyoka Hanawa,Japan,5.0,7.133,NaN,12.133,Qual,2019
12,13,Aneta Holasova,Czech Republic,5.0,7.100,NaN,12.100,Qual,2019
13,14,Nazli Savranbasi,Turkey,5.2,6.900,NaN,12.100,Qual,2019
14,15,Marine Boyer,France,4.9,7.066,NaN,11.966,Qual,2019
15,16,Tutya Yilmaz,Turkey,4.7,7.133,NaN,11.833,Qual,2019
16,17,An Chang Ok,North Korea,5.2,6.633,NaN,11.833,Qual,2019
17,18,Phoebe Jakubczyk,Great Britain,5.0,6.733,NaN,11.733,Qual,2019
18,19,Marta Pihan-Kulesza,Poland,5.2,6.500,NaN,11.700,Qual,2019
19,20,Lucie Jirikova,Czech Republic,4.2,7.066,NaN,11.266,Qual,2019
20,21,Marina Nekrasova,Azerbaijan,4.3,6.933,NaN,11.233,Qual,2019
21,22,Elisa Hämmerle,Austria,4.7,6.500,NaN,11.200,Qual,2019
22,23,Anina Wildi,Switzerland,4.3,6.633,NaN,10.933,Qual,2019
23,24,Gabriela Janik,Poland,4.3,6.166,NaN,10.466,Qual,2019
24,25,Ting Hua-Tien,Chinese Taipei,4.0,6.166,NaN,10.166,Qual,2019
25,26,Ruba Al Daoud,Jordan,2.8,5.600,-0.3,8.100,Qual,2019

In [26]:
ub["Nation"].unique()

array(['Belgium', 'China', 'Russia', 'Sweden', 'Germany', 'Italy',
       'Japan', 'Ukraine', 'Great Britain', 'Hungary', 'Czech Republic',
       'Turkey', 'France', 'North Korea', 'Poland', 'Azerbaijan',
       'Austria', 'Switzerland', 'Chinese Taipei', 'Jordan'], dtype=object)

In [27]:
# Dictionary mapping nation names to NOC codes
nation_to_noc = {
    'Belgium': 'BEL',
    'China': 'CHN',
    'Russia': 'RUS',
    'Sweden': 'SWE',
    'Germany': 'GER',
    'Italy': 'ITA',
    'Japan': 'JPN',
    'Ukraine': 'UKR',
    'Great Britain': 'GBR',
    'Hungary': 'HUN',
    'Czech Republic': 'CZE',
    'Turkey': 'TUR',
    'France': 'FRA',
    'North Korea': 'PRK',
    'Poland': 'POL',
    'Azerbaijan': 'AZE',
    'Austria': 'AUT',
    'Switzerland': 'SUI',
    'Chinese Taipei': 'TPE',
    'Jordan': 'JOR'
}

# Map the "Nations" column to NOC codes
ub['NOC'] = ub['Nation'].map(nation_to_noc)

In [28]:
ub

,Rank,Athlete,Nation,D,E,ND,Total,round,year,NOC
0,1,Nina Derwael,Belgium,6.5,8.533,NaN,15.033,Final,2019,BEL
1,2,Fan Yilin,China,6.5,8.433,NaN,14.933,Final,2019,CHN
2,3,Anastasiia Iliankova,Russia,6.3,8.400,NaN,14.700,Final,2019,RUS
3,4,Jonna Adlerteg,Sweden,6.0,8.216,NaN,14.216,Final,2019,SWE
4,5,Kim Bui,Germany,6.0,8.000,NaN,14.000,Final,2019,GER
5,6,Martina Rizzelli,Italy,5.1,7.916,NaN,13.016,Final,2019,ITA
6,7,Yumika Nakamura,Japan,5.1,7.833,NaN,12.933,Final,2019,JPN
7,8,Diana Varinska,Ukraine,5.0,7.400,NaN,12.400,Final,2019,UKR
0,1,Nina Derwael,Belgium,6.5,8.533,NaN,15.033,Qual,2019,BEL
1,2,Fan Yilin,China,6.3,8.600,NaN,14.900,Qual,2019,CHN
2,3,Anastasiia Iliankova,Russia,6.3,8.333,NaN,14.633,Qual,2019,RUS
3,4,Diana Varinska,Ukraine,5.7,8.266,NaN,13.966,Qual,2019,UKR
4,5,Kim Bui,Germany,6.0,7.900,NaN,13.900,Qual,2019,GER
5,6,Jonna Adlerteg,Sweden,6.0,7.366,NaN,13.366,Qual,2019,SWE
6,7,Martina Rizzelli,Italy,5.4,7.833,NaN,13.233,Qual,2019,ITA
7,8,Yumika Nakamura,Japan,5.1,8.000,NaN,13.100,Qual,2019,JPN
8,9,Lisa Katharina Hill,Germany,5.4,7.433,NaN,12.833,Qual,2019,GER
9,10,Emily Thomas,Great Britain,4.9,7.800,NaN,12.700,Qual,2019,GBR
10,11,Zoja Szekely,Hungary,6.0,6.700,NaN,12.700,Qual,2019,HUN
11,12,Soyoka Hanawa,Japan,5.0,7.133,NaN,12.133,Qual,2019,JPN
12,13,Aneta Holasova,Czech Republic,5.0,7.100,NaN,12.100,Qual,2019,CZE
13,14,Nazli Savranbasi,Turkey,5.2,6.900,NaN,12.100,Qual,2019,TUR
14,15,Marine Boyer,France,4.9,7.066,NaN,11.966,Qual,2019,FRA
15,16,Tutya Yilmaz,Turkey,4.7,7.133,NaN,11.833,Qual,2019,TUR
16,17,An Chang Ok,North Korea,5.2,6.633,NaN,11.833,Qual,2019,PRK
17,18,Phoebe Jakubczyk,Great Britain,5.0,6.733,NaN,11.733,Qual,2019,GBR
18,19,Marta Pihan-Kulesza,Poland,5.2,6.500,NaN,11.700,Qual,2019,POL
19,20,Lucie Jirikova,Czech Republic,4.2,7.066,NaN,11.266,Qual,2019,CZE
20,21,Marina Nekrasova,Azerbaijan,4.3,6.933,NaN,11.233,Qual,2019,AZE
21,22,Elisa Hämmerle,Austria,4.7,6.500,NaN,11.200,Qual,2019,AUT
22,23,Anina Wildi,Switzerland,4.3,6.633,NaN,10.933,Qual,2019,SUI
23,24,Gabriela Janik,Poland,4.3,6.166,NaN,10.466,Qual,2019,POL
24,25,Ting Hua-Tien,Chinese Taipei,4.0,6.166,NaN,10.166,Qual,2019,TPE
25,26,Ruba Al Daoud,Jordan,2.8,5.600,-0.3,8.100,Qual,2019,JOR

In [29]:
ub = ub.drop(columns=["Nation"])
ub["Nation"] = ub["NOC"]
ub = ub.drop(columns=["NOC"])

In [33]:
ub["ND"].fillna(0, inplace=True)

In [35]:
ub.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34 entries, 0 to 25
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     34 non-null     int64
 1   Athlete  34 non-null     object
 2   D        34 non-null     float64
 3   E        34 non-null     float64
 4   ND       34 non-null     float64
 5   Total    34 non-null     float64
 6   round    34 non-null     object
 7   year     34 non-null     int64
 8   Nation   34 non-null     object
dtypes: float64(4), int64(2), object(3)
memory usage: 2.7+ KB

In [37]:
# ub.to_csv('clean_worldcup2019doha_ub.csv', index=False)
# bb.to_csv('clean_worldcup2019doha_bb.csv', index=False)

In [39]:
fx.head()

   Rank              Athlete         Nation    D      E   ND   Total
0     1           Jade Carey  United States  6.2  8.266  NaN  14.466
1     2            Lara Mori          Italy  5.6  7.833  NaN  13.433
2     3      Vanessa Ferrari          Italy  5.2  8.100  NaN  13.300
3     4  Marta Pihan-Kulesza         Poland  5.4  7.933 -0.1  13.233
4     5         Marine Boyer         France  5.0  8.200  NaN  13.200

In [40]:
fxq.head()

   Rank         Athlete         Nation    D      E   ND   Total round
0     1      Jade Carey  United States  5.9  8.200 -0.1  14.000  Qual
1     2    Marine Boyer         France  5.0  8.200  NaN  13.200  Qual
2     3         Kim Bui        Germany  5.2  8.000  NaN  13.200  Qual
3     4       Lara Mori          Italy  5.3  7.866  NaN  13.166  Qual
4     5  Varvara Zubova         Russia  5.1  7.966  NaN  13.066  Qual

In [41]:
fx["round"] = "Final"

In [42]:
combined_df = pd.concat([fx, fxq], axis=0)

In [43]:
fx = combined_df.copy()

In [45]:
fx['year']=2019

In [46]:
fx["ND"].fillna(0, inplace=True)

In [48]:
fx["Nation"].uniqueue()

array(['United States', 'Italy', 'Poland', 'France', 'Russia', 'Germany',
       'Great Britain', 'Ukraine', 'Croatia', 'Turkey', 'Puerto Rico',
       'Czech Republic', 'Slovenia', 'North Korea', 'Japan', 'China',
       'Chinese Taipei', 'Hungary', 'Uzbekistan', 'Azerbaijan', 'Cuba'],
      dtype=object)

In [50]:

# Dictionary mapping nation names to NOC codes
nation_to_noc = {
    'United States': 'USA',
    'Italy': 'ITA',
    'Poland': 'POL',
    'France': 'FRA',
    'Russia': 'RUS',
    'Germany': 'GER',
    'Great Britain': 'GBR',
    'Ukraine': 'UKR',
    'Croatia': 'CRO',
    'Turkey': 'TUR',
    'Puerto Rico': 'PUR',
    'Czech Republic': 'CZE',
    'Slovenia': 'SLO',
    'North Korea': 'PRK',
    'Japan': 'JPN',
    'China': 'CHN',
    'Chinese Taipei': 'TPE',
    'Hungary': 'HUN',
    'Uzbekistan': 'UZB',
    'Azerbaijan': 'AZE',
    'Cuba': 'CUB'
}

# Map the "Nations" coumn to NOC codes
fx['NOC'] = fx['Nation'].map(nation_to_noc)

In [51]:
fx

,Rank,Athlete,Nation,D,E,ND,Total,round,year,NOC
0,1,Jade Carey,United States,6.2,8.266,0.0,14.466,Final,2019,USA
1,2,Lara Mori,Italy,5.6,7.833,0.0,13.433,Final,2019,ITA
2,3,Vanessa Ferrari,Italy,5.2,8.100,0.0,13.300,Final,2019,ITA
3,4,Marta Pihan-Kulesza,Poland,5.4,7.933,-0.1,13.233,Final,2019,POL
4,5,Marine Boyer,France,5.0,8.200,0.0,13.200,Final,2019,FRA
5,6,Varvara Zubova,Russia,5.1,8.000,0.0,13.100,Final,2019,RUS
6,7,Kim Bui,Germany,5.2,7.833,0.0,13.033,Final,2019,GER
7,8,Coline Devillard,France,4.8,7.900,-0.3,12.400,Final,2019,FRA
0,1,Jade Carey,United States,5.9,8.200,-0.1,14.000,Qual,2019,USA
1,2,Marine Boyer,France,5.0,8.200,0.0,13.200,Qual,2019,FRA
2,3,Kim Bui,Germany,5.2,8.000,0.0,13.200,Qual,2019,GER
3,4,Lara Mori,Italy,5.3,7.866,0.0,13.166,Qual,2019,ITA
4,5,Varvara Zubova,Russia,5.1,7.966,0.0,13.066,Qual,2019,RUS
5,6,Marta Pihan-Kulesza,Poland,5.2,7.933,-0.1,13.033,Qual,2019,POL
6,7,Vanessa Ferrari,Italy,5.3,7.833,-0.1,13.033,Qual,2019,ITA
7,8,Coline Devillard,France,4.8,8.033,0.0,12.833,Qual,2019,FRA
8,9,Phoebe Jakubczyk,Great Britain,5.0,7.833,0.0,12.833,Qual,2019,GBR
9,10,Diana Varinska,Ukraine,4.7,8.066,0.0,12.766,Qual,2019,UKR
10,11,Emily Thomas,Great Britain,4.8,7.966,0.0,12.766,Qual,2019,GBR
11,12,Ana Derek,Croatia,5.0,7.833,-0.1,12.733,Qual,2019,CRO
12,13,Nazli Savranbasi,Turkey,5.0,7.600,0.0,12.600,Qual,2019,TUR
13,14,Paula Mejias,Puerto Rico,5.1,7.466,-0.1,12.466,Qual,2019,PUR
14,15,Aneta Holasova,Czech Republic,4.7,7.833,-0.1,12.433,Qual,2019,CZE
15,16,Adela Sajn,Slovenia,4.4,8.000,0.0,12.400,Qual,2019,SLO
16,17,Kim Son Hyang,North Korea,5.3,7.200,-0.1,12.400,Qual,2019,PRK
17,18,Yumika Nakamura,Japan,4.6,7.766,0.0,12.366,Qual,2019,JPN
18,19,Soyoka Hanawa,Japan,4.8,7.466,0.0,12.266,Qual,2019,JPN
19,20,Zhao Shiting,China,5.1,7.100,0.0,12.200,Qual,2019,CHN
20,21,Lai Pin-Ju,Chinese Taipei,4.7,7.300,0.0,12.000,Qual,2019,TPE
21,22,An Chang Ok,North Korea,5.0,6.933,0.0,11.933,Qual,2019,PRK
22,23,Csenge Bacskay,Hungary,4.4,7.433,-0.1,11.733,Qual,2019,HUN
23,24,Demet Mutlu,Turkey,4.6,6.900,0.0,11.500,Qual,2019,TUR
24,25,Wu Sing-Fen,Chinese Taipei,4.1,7.366,0.0,11.466,Qual,2019,TPE
25,26,Ominakhon Khalilova,Uzbekistan,4.6,7.166,-0.3,11.466,Qual,2019,UZB
26,27,Lucie Jirikova,Czech Republic,4.7,6.500,0.0,11.200,Qual,2019,CZE
27,28,Gabriela Janik,Poland,4.5,6.933,-0.3,11.133,Qual,2019,POL
28,29,Marina Nekrasova,Azerbaijan,4.1,6.666,0.0,10.766,Qual,2019,AZE
29,30,Marcia Vidiaux,Cuba,2.5,7.500,-0.1,9.900,Qual,2019,CUB

In [52]:
fx.info()

<class 'pandas.core.frame.DataFrame'>
Index: 38 entries, 0 to 29
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     38 non-null     int64
 1   Athlete  38 non-null     object
 2   Nation   38 non-null     object
 3   D        38 non-null     float64
 4   E        38 non-null     float64
 5   ND       38 non-null     float64
 6   Total    38 non-null     float64
 7   round    38 non-null     object
 8   year     38 non-null     int64
 9   NOC      38 non-null     object
dtypes: float64(4), int64(2), object(4)
memory usage: 3.3+ KB

In [53]:
vt

,Rank,Athlete,Nation,D,E,ND,Total,d2,e2,pen2,score2,Average
0,1,Jade Carey,United States,6.0,9.066,NaN,15.066,5.4,9.300,NaN,14.700,14.883
1,2,Maria Paseka,Russia,6.0,8.533,-0.1,14.433,5.8,9.300,NaN,15.100,14.766
2,3,Coline Devillard,France,5.8,9.133,NaN,14.933,5.4,8.766,NaN,14.166,14.549
3,4,Alexa Moreno,Mexico,5.8,8.700,-0.1,14.400,5.6,8.800,NaN,14.400,14.400
4,5,Oksana Chusovitina,Uzbekistan,5.2,8.666,NaN,13.866,5.2,8.766,-0.1,13.866,13.866
5,6,Emily Thomas,Great Britain,5.0,9.033,NaN,14.033,4.8,8.866,NaN,13.666,13.849
6,7,Gabriela Janik,Poland,4.8,8.866,NaN,13.666,4.8,8.966,NaN,13.766,13.716
7,8,Marina Nekrasova,Azerbaijan,4.8,7.533,NaN,12.333,5.4,8.800,-0.1,14.100,13.216

In [55]:
null_counts = {}

# Iterate through columns and count null values for each column
for column in vt.columns:
    null_count = vt[column].isnull().sum()
    null_counts[column] = null_count

# Print the null counts for each column
for column, count in null_counts.items():
    print(f'Column "{column}" has {count} null values.')

Column "Rank" has 0 null values.
Column "Athlete" has 0 null values.
Column "Nation" has 0 null values.
Column "D" has 0 null values.
Column "E" has 0 null values.
Column "ND" has 6 null values.
Column "Total" has 0 null values.
Column "d2" has 0 null values.
Column "e2" has 0 null values.
Column "pen2" has 6 null values.
Column "score2" has 0 null values.
Column "Average" has 0 null values.

In [56]:
vt.fillna(0, inplace=True)

In [57]:
vt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 12 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     8 non-null      int64
 1   Athlete  8 non-null      object
 2   Nation   8 non-null      object
 3   D        8 non-null      float64
 4   E        8 non-null      float64
 5   ND       8 non-null      float64
 6   Total    8 non-null      float64
 7   d2       8 non-null      float64
 8   e2       8 non-null      float64
 9   pen2     8 non-null      float64
 10  score2   8 non-null      float64
 11  Average  8 non-null      float64
dtypes: float64(9), int64(1), object(2)
memory usage: 896.0+ bytes

In [58]:
# fx.to_csv('clean_worldcup2019doha_fx.csv', index=False)
# vt.to_csv('clean_worldcup2019doha_vt.csv', index=False)