In [1]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("../../scraping/olympics/olympic2012men_final/Gymnastics_ 2012_Olympics_Men's_artistic_team_all-around.csv")

In [8]:
df

,Team,fx,fx_Rank,ph,ph_Rank,sr,sr_Rank,vt,vt_Rank,pb,pb_Rank,hb,hb_Rank,tota;,total_Rank
0,China,45.133,5.0,43.8330,4.0,44.899,5.0,48.316,1.0,46.750,1.0,47.066,1.0,275.997,1.0
1,Chen Yibing(CHN),NaN,NaN,14.7330,11.0,15.800,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Feng Zhe(CHN),14.400,21.0,NaN,NaN,14.533,20.0,16.216,4.0,15.950,1.0,15.000,14.0,NaN,NaN
3,Guo Weiyang(CHN),NaN,NaN,14.6000,14.0,14.566,19.0,NaN,NaN,15.200,13.0,NaN,NaN,NaN,NaN
4,Zhang Chenglong(CHN),14.900,14.0,14.5000,16.0,NaN,NaN,16.200,5.0,15.600,2.0,15.666,6.0,NaN,NaN
5,Zou Kai(CHN),15.833,1.0,NaN,NaN,NaN,NaN,15.900,12.0,NaN,NaN,16.400,1.0,NaN,NaN
6,Japan,44.733,6.0,42.3650,5.0,45.699,2.0,45.971,7.0,46.282,2.0,46.899,2.0,271.952,2.0
7,Ryōhei Katō(JPN),15.300,8.0,14.7660,9.0,NaN,NaN,16.041,9.0,NaN,NaN,NaN,NaN,NaN,NaN
8,Kazuhito Tanaka(JPN),13.733,24.0,13.4330,19.0,NaN,NaN,NaN,NaN,15.366,10.0,15.166,12.0,NaN,NaN
9,Yusuke Tanaka(JPN),NaN,NaN,NaN,NaN,15.200,8.0,NaN,NaN,15.500,5.0,16.000,3.0,NaN,NaN
10,Kōhei Uchimura(JPN),15.700,2.0,14.1661,18.0,15.133,9.0,15.900,12.0,15.416,8.0,15.733,5.0,NaN,NaN
11,Koji Yamamuro(JPN),NaN,NaN,NaN,NaN,15.366,5.0,14.033,24.0,NaN,NaN,NaN,NaN,NaN,NaN
12,Great Britain,46.132,1.0,45.9320,1.0,43.066,8.0,48.182,2.0,44.566,7.0,43.833,7.0,271.711,3.0
13,Sam Oldham(GBR),NaN,NaN,NaN,NaN,14.033,24.0,NaN,NaN,14.966,18.0,14.000,22.0,NaN,NaN
14,Daniel Purvis(GBR),15.533,3.0,14.7330,11.0,14.600,18.0,15.966,10.0,14.800,19.0,14.633,18.0,NaN,NaN
15,Louis Smith(GBR),NaN,NaN,15.9660,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Kristian Thomas(GBR),15.433,6.0,NaN,NaN,14.433,22.0,16.550,1.0,NaN,NaN,15.200,10.0,NaN,NaN
17,Max Whitlock(GBR),15.166,11.0,15.2330,3.0,NaN,NaN,15.666,16.0,14.800,19.0,NaN,NaN,NaN,NaN
18,Ukraine,44.065,8.0,44.9660,3.0,45.699,2.0,48.065,3.0,44.733,6.0,43.998,6.0,271.526,4.0
19,Nikolai Kuksenkov(UKR),NaN,NaN,15.1000,4.0,15.233,7.0,NaN,NaN,15.200,13.0,15.266,9.0,NaN,NaN
20,Vitaliy Nakonechnyi(UKR),14.333,22.0,14.8660,7.0,NaN,NaN,NaN,NaN,NaN,NaN,14.266,21.0,NaN,NaN
21,Igor Radivilov(UKR),NaN,NaN,NaN,NaN,15.433,4.0,16.066,7.0,NaN,NaN,NaN,NaN,NaN,NaN
22,Oleg Stepko(UKR),14.866,16.0,15.0000,6.0,15.033,11.0,15.733,15.0,13.933,23.0,NaN,NaN,NaN,NaN
23,Oleg Verniaiev(UKR),14.866,16.0,NaN,NaN,NaN,NaN,16.266,3.0,15.600,2.0,14.466,20.0,NaN,NaN
24,United States,45.266,3.0,40.6330,7.0,45.257,4.0,46.632,6.0,45.765,3.0,46.399,3.0,269.952,5.0
25,Jake Dalton(USA),15.466,5.0,NaN,NaN,15.033,11.0,16.066,7.0,NaN,NaN,NaN,NaN,NaN,NaN
26,Jonathan Horton(USA),NaN,NaN,NaN,NaN,15.266,7.0,NaN,NaN,NaN,NaN,15.200,10.0,NaN,NaN
27,Danell Leyva(USA),15.200,9.0,13.4000,20.0,NaN,NaN,NaN,NaN,15.366,10.0,15.866,4.0,NaN,NaN
28,Sam Mikulak(USA),14.600,19.0,14.5000,16.0,NaN,NaN,15.966,10.0,15.266,12.0,NaN,NaN,NaN,NaN
29,John Orozco(USA),NaN,NaN,12.7330,23.0,14.958,13.0,14.600,20.0,15.133,15.0,15.333,8.0,NaN,NaN
30,Russia,45.308,2.0,42.2990,6.0,46.132,1.0,46.866,5.0,43.965,8.0,45.033,5.0,269.603,6.0
31,Denis Ablyazin(RUS),15.475,4.0,NaN,NaN,15.616,3.0,16.400,2.0,NaN,NaN,NaN,NaN,NaN,NaN
32,Aleksandr Balandin(RUS),NaN,NaN,NaN,NaN,15.816,1.0,NaN,NaN,13.466,24.0,NaN,NaN,NaN,NaN
33,David Belyavskiy(RUS),14.933,13.0,12.9330,22.0,NaN,NaN,16.133,6.0,15.433,7.0,14.833,16.0,NaN,NaN
34,Emin Garibov(RUS),NaN,NaN,14.8330,8.0,14.700,16.0,NaN,NaN,15.066,17.0,15.600,7.0,NaN,NaN
35,Igor Pakhomenko(RUS),14.900,14.0,14.5330,15.0,NaN,NaN,14.333,23.0,NaN,NaN,14.600,19.0,NaN,NaN
36,Germany,45.199,4.0,40.4660,8.0,44.824,6.0,47.032,4.0,45.433,4.0,45.065,4.0,268.019,7.0
37,Philipp Boy(GER),14.800,18.0,13.2000,21.0,NaN,NaN,15.566,18.0,NaN,NaN,13.766,23.0,NaN,NaN
38,Fabian Hambüchen(GER),15.066,12.0,NaN,NaN,14.858,14.0,15.633,17.0,15.400,9.0,16.166,2.0,NaN,NaN
39,Sebastian Krimmer(GER),NaN,NaN,14.7330,11.0,NaN,NaN,NaN,NaN,14.533,22.0,NaN,NaN,NaN,NaN
40,Marcel Nguyen(GER),15.333,7.0,NaN,NaN,15.133,9.0,15.833,14.0,15.500,5.0,15.133,13.0,NaN,NaN
41,Andreas Toba(GER),NaN,NaN,12.5330,24.0,14.833,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,France,44.066,7.0,45.2650,2.0,43.432,7.0,44.473,8.0,45.290,5.0,42.915,8.0,265.441,8.0
43,Pierre-Yves Bény(FRA),14.333,22.0,15.0330,5.0,14.466,21.0,14.566,21.0,14.591,21.0,13.266,24.0,NaN,NaN
44,Yann Cucherat(FRA),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Gaël da Silva(FRA),15.200,9.0,NaN,NaN,14.633,17.0,15.466,19.0,NaN,NaN,14.766,17.0,NaN,NaN
46,Hamilton Sabot(FRA),NaN,NaN,14.7660,9.0,14.333,23.0,NaN,NaN,15.566,4.0,14.833,15.0,NaN,NaN
47,Cyril Tommasone(FRA),14.533,20.0,15.4660,2.0,NaN,NaN,14.441,22.0,15.133,15.0,NaN,NaN,NaN,NaN

In [9]:
new_df = df.iloc[::6]

# Reset index in the new DataFrame
new_df.reset_index(drop=True, inplace=True)

In [10]:
new_df

,Team,fx,fx_Rank,ph,ph_Rank,sr,sr_Rank,vt,vt_Rank,pb,pb_Rank,hb,hb_Rank,tota;,total_Rank
0,China,45.133,5.0,43.833,4.0,44.899,5.0,48.316,1.0,46.750,1.0,47.066,1.0,275.997,1.0
1,Japan,44.733,6.0,42.365,5.0,45.699,2.0,45.971,7.0,46.282,2.0,46.899,2.0,271.952,2.0
2,Great Britain,46.132,1.0,45.932,1.0,43.066,8.0,48.182,2.0,44.566,7.0,43.833,7.0,271.711,3.0
3,Ukraine,44.065,8.0,44.966,3.0,45.699,2.0,48.065,3.0,44.733,6.0,43.998,6.0,271.526,4.0
4,United States,45.266,3.0,40.633,7.0,45.257,4.0,46.632,6.0,45.765,3.0,46.399,3.0,269.952,5.0
5,Russia,45.308,2.0,42.299,6.0,46.132,1.0,46.866,5.0,43.965,8.0,45.033,5.0,269.603,6.0
6,Germany,45.199,4.0,40.466,8.0,44.824,6.0,47.032,4.0,45.433,4.0,45.065,4.0,268.019,7.0
7,France,44.066,7.0,45.265,2.0,43.432,7.0,44.473,8.0,45.290,5.0,42.915,8.0,265.441,8.0

In [11]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Team        8 non-null      object
 1   fx          8 non-null      float64
 2   fx_Rank     8 non-null      float64
 3   ph          8 non-null      float64
 4   ph_Rank     8 non-null      float64
 5   sr          8 non-null      float64
 6   sr_Rank     8 non-null      float64
 7   vt          8 non-null      float64
 8   vt_Rank     8 non-null      float64
 9   pb          8 non-null      float64
 10  pb_Rank     8 non-null      float64
 11  hb          8 non-null      float64
 12  hb_Rank     8 non-null      float64
 13  tota;       8 non-null      float64
 14  total_Rank  8 non-null      float64
dtypes: float64(14), object(1)
memory usage: 1.1+ KB

In [12]:
# new_df.to_csv('clean2012Olympics_Men\'s_artistic_team_all-around.csv', index=False)

In [14]:
# Remove rows where "Rank" is not NaN
df = df[df['total_Rank'].isna()]

# Reset the index if needed
df.reset_index(drop=True, inplace=True)

In [15]:
df

,Team,fx,fx_Rank,ph,ph_Rank,sr,sr_Rank,vt,vt_Rank,pb,pb_Rank,hb,hb_Rank,tota;,total_Rank
0,Chen Yibing(CHN),NaN,NaN,14.7330,11.0,15.800,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Feng Zhe(CHN),14.400,21.0,NaN,NaN,14.533,20.0,16.216,4.0,15.950,1.0,15.000,14.0,NaN,NaN
2,Guo Weiyang(CHN),NaN,NaN,14.6000,14.0,14.566,19.0,NaN,NaN,15.200,13.0,NaN,NaN,NaN,NaN
3,Zhang Chenglong(CHN),14.900,14.0,14.5000,16.0,NaN,NaN,16.200,5.0,15.600,2.0,15.666,6.0,NaN,NaN
4,Zou Kai(CHN),15.833,1.0,NaN,NaN,NaN,NaN,15.900,12.0,NaN,NaN,16.400,1.0,NaN,NaN
5,Ryōhei Katō(JPN),15.300,8.0,14.7660,9.0,NaN,NaN,16.041,9.0,NaN,NaN,NaN,NaN,NaN,NaN
6,Kazuhito Tanaka(JPN),13.733,24.0,13.4330,19.0,NaN,NaN,NaN,NaN,15.366,10.0,15.166,12.0,NaN,NaN
7,Yusuke Tanaka(JPN),NaN,NaN,NaN,NaN,15.200,8.0,NaN,NaN,15.500,5.0,16.000,3.0,NaN,NaN
8,Kōhei Uchimura(JPN),15.700,2.0,14.1661,18.0,15.133,9.0,15.900,12.0,15.416,8.0,15.733,5.0,NaN,NaN
9,Koji Yamamuro(JPN),NaN,NaN,NaN,NaN,15.366,5.0,14.033,24.0,NaN,NaN,NaN,NaN,NaN,NaN
10,Sam Oldham(GBR),NaN,NaN,NaN,NaN,14.033,24.0,NaN,NaN,14.966,18.0,14.000,22.0,NaN,NaN
11,Daniel Purvis(GBR),15.533,3.0,14.7330,11.0,14.600,18.0,15.966,10.0,14.800,19.0,14.633,18.0,NaN,NaN
12,Louis Smith(GBR),NaN,NaN,15.9660,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Kristian Thomas(GBR),15.433,6.0,NaN,NaN,14.433,22.0,16.550,1.0,NaN,NaN,15.200,10.0,NaN,NaN
14,Max Whitlock(GBR),15.166,11.0,15.2330,3.0,NaN,NaN,15.666,16.0,14.800,19.0,NaN,NaN,NaN,NaN
15,Nikolai Kuksenkov(UKR),NaN,NaN,15.1000,4.0,15.233,7.0,NaN,NaN,15.200,13.0,15.266,9.0,NaN,NaN
16,Vitaliy Nakonechnyi(UKR),14.333,22.0,14.8660,7.0,NaN,NaN,NaN,NaN,NaN,NaN,14.266,21.0,NaN,NaN
17,Igor Radivilov(UKR),NaN,NaN,NaN,NaN,15.433,4.0,16.066,7.0,NaN,NaN,NaN,NaN,NaN,NaN
18,Oleg Stepko(UKR),14.866,16.0,15.0000,6.0,15.033,11.0,15.733,15.0,13.933,23.0,NaN,NaN,NaN,NaN
19,Oleg Verniaiev(UKR),14.866,16.0,NaN,NaN,NaN,NaN,16.266,3.0,15.600,2.0,14.466,20.0,NaN,NaN
20,Jake Dalton(USA),15.466,5.0,NaN,NaN,15.033,11.0,16.066,7.0,NaN,NaN,NaN,NaN,NaN,NaN
21,Jonathan Horton(USA),NaN,NaN,NaN,NaN,15.266,7.0,NaN,NaN,NaN,NaN,15.200,10.0,NaN,NaN
22,Danell Leyva(USA),15.200,9.0,13.4000,20.0,NaN,NaN,NaN,NaN,15.366,10.0,15.866,4.0,NaN,NaN
23,Sam Mikulak(USA),14.600,19.0,14.5000,16.0,NaN,NaN,15.966,10.0,15.266,12.0,NaN,NaN,NaN,NaN
24,John Orozco(USA),NaN,NaN,12.7330,23.0,14.958,13.0,14.600,20.0,15.133,15.0,15.333,8.0,NaN,NaN
25,Denis Ablyazin(RUS),15.475,4.0,NaN,NaN,15.616,3.0,16.400,2.0,NaN,NaN,NaN,NaN,NaN,NaN
26,Aleksandr Balandin(RUS),NaN,NaN,NaN,NaN,15.816,1.0,NaN,NaN,13.466,24.0,NaN,NaN,NaN,NaN
27,David Belyavskiy(RUS),14.933,13.0,12.9330,22.0,NaN,NaN,16.133,6.0,15.433,7.0,14.833,16.0,NaN,NaN
28,Emin Garibov(RUS),NaN,NaN,14.8330,8.0,14.700,16.0,NaN,NaN,15.066,17.0,15.600,7.0,NaN,NaN
29,Igor Pakhomenko(RUS),14.900,14.0,14.5330,15.0,NaN,NaN,14.333,23.0,NaN,NaN,14.600,19.0,NaN,NaN
30,Philipp Boy(GER),14.800,18.0,13.2000,21.0,NaN,NaN,15.566,18.0,NaN,NaN,13.766,23.0,NaN,NaN
31,Fabian Hambüchen(GER),15.066,12.0,NaN,NaN,14.858,14.0,15.633,17.0,15.400,9.0,16.166,2.0,NaN,NaN
32,Sebastian Krimmer(GER),NaN,NaN,14.7330,11.0,NaN,NaN,NaN,NaN,14.533,22.0,NaN,NaN,NaN,NaN
33,Marcel Nguyen(GER),15.333,7.0,NaN,NaN,15.133,9.0,15.833,14.0,15.500,5.0,15.133,13.0,NaN,NaN
34,Andreas Toba(GER),NaN,NaN,12.5330,24.0,14.833,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Pierre-Yves Bény(FRA),14.333,22.0,15.0330,5.0,14.466,21.0,14.566,21.0,14.591,21.0,13.266,24.0,NaN,NaN
36,Yann Cucherat(FRA),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Gaël da Silva(FRA),15.200,9.0,NaN,NaN,14.633,17.0,15.466,19.0,NaN,NaN,14.766,17.0,NaN,NaN
38,Hamilton Sabot(FRA),NaN,NaN,14.7660,9.0,14.333,23.0,NaN,NaN,15.566,4.0,14.833,15.0,NaN,NaN
39,Cyril Tommasone(FRA),14.533,20.0,15.4660,2.0,NaN,NaN,14.441,22.0,15.133,15.0,NaN,NaN,NaN,NaN

In [16]:
dfg = df.copy()

In [17]:

import re

dfg['country'] = None

# Iterate through the "Unnamed: 2" column, extract values within parentheses, and store them in "Vault Rank" column
for index, row in dfg.iterrows():
    value = row['Team']
    if value is not None:
        match = re.search(r'\((.*?)\)', value)
        if match:
            Teams_rank = match.group(1)
            dfg.at[index, 'country'] = Teams_rank



# Remove parentheses and their contents from "Unnamed: 2" column
dfg['Team'] = dfg['Team'].apply(lambda x: re.sub(r'\([^)]*\)', '', str(x)))

In [18]:
df = dfg.copy()

In [19]:
df.columns

Index(['Team', 'fx', 'fx_Rank', 'ph', 'ph_Rank', 'sr', 'sr_Rank', 'vt',
       'vt_Rank', 'pb', 'pb_Rank', 'hb', 'hb_Rank', 'tota;', 'total_Rank',
       'country'],
      dtype='object')

In [20]:
column_order = ['Team','country', 'fx', 'fx_Rank', 'ph', 'ph_Rank', 'sr', 'sr_Rank', 'vt',
       'vt_Rank', 'pb', 'pb_Rank', 'hb', 'hb_Rank', 'tota;', 'total_Rank',
       ]
# Create a new DataFrame with the desired column order
df = df[column_order]

In [21]:
df = df.drop(columns=["tota;", "total_Rank"])

In [22]:
df

,Team,country,fx,fx_Rank,ph,ph_Rank,sr,sr_Rank,vt,vt_Rank,pb,pb_Rank,hb,hb_Rank
0,Chen Yibing,CHN,NaN,NaN,14.7330,11.0,15.800,2.0,NaN,NaN,NaN,NaN,NaN,NaN
1,Feng Zhe,CHN,14.400,21.0,NaN,NaN,14.533,20.0,16.216,4.0,15.950,1.0,15.000,14.0
2,Guo Weiyang,CHN,NaN,NaN,14.6000,14.0,14.566,19.0,NaN,NaN,15.200,13.0,NaN,NaN
3,Zhang Chenglong,CHN,14.900,14.0,14.5000,16.0,NaN,NaN,16.200,5.0,15.600,2.0,15.666,6.0
4,Zou Kai,CHN,15.833,1.0,NaN,NaN,NaN,NaN,15.900,12.0,NaN,NaN,16.400,1.0
5,Ryōhei Katō,JPN,15.300,8.0,14.7660,9.0,NaN,NaN,16.041,9.0,NaN,NaN,NaN,NaN
6,Kazuhito Tanaka,JPN,13.733,24.0,13.4330,19.0,NaN,NaN,NaN,NaN,15.366,10.0,15.166,12.0
7,Yusuke Tanaka,JPN,NaN,NaN,NaN,NaN,15.200,8.0,NaN,NaN,15.500,5.0,16.000,3.0
8,Kōhei Uchimura,JPN,15.700,2.0,14.1661,18.0,15.133,9.0,15.900,12.0,15.416,8.0,15.733,5.0
9,Koji Yamamuro,JPN,NaN,NaN,NaN,NaN,15.366,5.0,14.033,24.0,NaN,NaN,NaN,NaN
10,Sam Oldham,GBR,NaN,NaN,NaN,NaN,14.033,24.0,NaN,NaN,14.966,18.0,14.000,22.0
11,Daniel Purvis,GBR,15.533,3.0,14.7330,11.0,14.600,18.0,15.966,10.0,14.800,19.0,14.633,18.0
12,Louis Smith,GBR,NaN,NaN,15.9660,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Kristian Thomas,GBR,15.433,6.0,NaN,NaN,14.433,22.0,16.550,1.0,NaN,NaN,15.200,10.0
14,Max Whitlock,GBR,15.166,11.0,15.2330,3.0,NaN,NaN,15.666,16.0,14.800,19.0,NaN,NaN
15,Nikolai Kuksenkov,UKR,NaN,NaN,15.1000,4.0,15.233,7.0,NaN,NaN,15.200,13.0,15.266,9.0
16,Vitaliy Nakonechnyi,UKR,14.333,22.0,14.8660,7.0,NaN,NaN,NaN,NaN,NaN,NaN,14.266,21.0
17,Igor Radivilov,UKR,NaN,NaN,NaN,NaN,15.433,4.0,16.066,7.0,NaN,NaN,NaN,NaN
18,Oleg Stepko,UKR,14.866,16.0,15.0000,6.0,15.033,11.0,15.733,15.0,13.933,23.0,NaN,NaN
19,Oleg Verniaiev,UKR,14.866,16.0,NaN,NaN,NaN,NaN,16.266,3.0,15.600,2.0,14.466,20.0
20,Jake Dalton,USA,15.466,5.0,NaN,NaN,15.033,11.0,16.066,7.0,NaN,NaN,NaN,NaN
21,Jonathan Horton,USA,NaN,NaN,NaN,NaN,15.266,7.0,NaN,NaN,NaN,NaN,15.200,10.0
22,Danell Leyva,USA,15.200,9.0,13.4000,20.0,NaN,NaN,NaN,NaN,15.366,10.0,15.866,4.0
23,Sam Mikulak,USA,14.600,19.0,14.5000,16.0,NaN,NaN,15.966,10.0,15.266,12.0,NaN,NaN
24,John Orozco,USA,NaN,NaN,12.7330,23.0,14.958,13.0,14.600,20.0,15.133,15.0,15.333,8.0
25,Denis Ablyazin,RUS,15.475,4.0,NaN,NaN,15.616,3.0,16.400,2.0,NaN,NaN,NaN,NaN
26,Aleksandr Balandin,RUS,NaN,NaN,NaN,NaN,15.816,1.0,NaN,NaN,13.466,24.0,NaN,NaN
27,David Belyavskiy,RUS,14.933,13.0,12.9330,22.0,NaN,NaN,16.133,6.0,15.433,7.0,14.833,16.0
28,Emin Garibov,RUS,NaN,NaN,14.8330,8.0,14.700,16.0,NaN,NaN,15.066,17.0,15.600,7.0
29,Igor Pakhomenko,RUS,14.900,14.0,14.5330,15.0,NaN,NaN,14.333,23.0,NaN,NaN,14.600,19.0
30,Philipp Boy,GER,14.800,18.0,13.2000,21.0,NaN,NaN,15.566,18.0,NaN,NaN,13.766,23.0
31,Fabian Hambüchen,GER,15.066,12.0,NaN,NaN,14.858,14.0,15.633,17.0,15.400,9.0,16.166,2.0
32,Sebastian Krimmer,GER,NaN,NaN,14.7330,11.0,NaN,NaN,NaN,NaN,14.533,22.0,NaN,NaN
33,Marcel Nguyen,GER,15.333,7.0,NaN,NaN,15.133,9.0,15.833,14.0,15.500,5.0,15.133,13.0
34,Andreas Toba,GER,NaN,NaN,12.5330,24.0,14.833,15.0,NaN,NaN,NaN,NaN,NaN,NaN
35,Pierre-Yves Bény,FRA,14.333,22.0,15.0330,5.0,14.466,21.0,14.566,21.0,14.591,21.0,13.266,24.0
36,Yann Cucherat,FRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Gaël da Silva,FRA,15.200,9.0,NaN,NaN,14.633,17.0,15.466,19.0,NaN,NaN,14.766,17.0
38,Hamilton Sabot,FRA,NaN,NaN,14.7660,9.0,14.333,23.0,NaN,NaN,15.566,4.0,14.833,15.0
39,Cyril Tommasone,FRA,14.533,20.0,15.4660,2.0,NaN,NaN,14.441,22.0,15.133,15.0,NaN,NaN

In [23]:
df.fillna(0, inplace=True)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Team     40 non-null     object
 1   country  40 non-null     object
 2   fx       40 non-null     float64
 3   fx_Rank  40 non-null     float64
 4   ph       40 non-null     float64
 5   ph_Rank  40 non-null     float64
 6   sr       40 non-null     float64
 7   sr_Rank  40 non-null     float64
 8   vt       40 non-null     float64
 9   vt_Rank  40 non-null     float64
 10  pb       40 non-null     float64
 11  pb_Rank  40 non-null     float64
 12  hb       40 non-null     float64
 13  hb_Rank  40 non-null     float64
dtypes: float64(12), object(2)
memory usage: 4.5+ KB

In [25]:
# df.to_csv('clean2012Olympics_Men\'s_artistic_team_all-around_Individuals.csv', index=False)