In [1]:
import ipywidgets as widgets
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets
from ipywidgets import interact
import ipywidgets as widgets
from ipywidgets import interact

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('./Team Selection/men/all_usa.csv')
df1 = pd.read_csv('./Team Selection/men/top_men.csv')
df2 = pd.read_csv('./Team Selection/men/usa_men.csv')
iaa = pd.read_csv('./Combine_Data/men/iaa2024.csv')

In [4]:
# df2[df2['Athlete']=='vitaliy guimaraes']

In [5]:
# iaa[iaa['Athlete'] =='vitaliy guimaraes']

In [6]:
# df[df['Name']=='vitaliy guimaraes']

In [7]:
dfs=iaa.copy()

In [8]:
# import pandas as pd
# from scipy.stats import percentileofscore

# # Your DataFrame
# # df = ...

# iaa = iaa.drop(columns=['Rank', 'round','Nation' ,'year'])

# # Athlete of interest
# athlete_name = 'vitaliy guimaraes'

# # Create a dictionary to store percentiles for each apparatus
# percentiles_dict = {}

# for apparatus in iaa.columns[1:-1]:  # Exclude 'Athlete' and 'AA' columns
#     scores = iaa[apparatus].values
#     athlete_score = iaa[iaa['Athlete'] == athlete_name][apparatus].values[0]
    
#     # Calculate percentile
#     percentile = percentileofscore(scores, athlete_score)
#     percentiles_dict[apparatus] = percentile

# # Display percentiles
# for apparatus, percentile in percentiles_dict.items():
#     print(f"{athlete_name} is in the {percentile:.2f} percentile for {apparatus}")

In [9]:
usa=dfs[dfs['Nation']=='USA']

In [10]:
usa

,Rank,Athlete,FX,PH,SR,VT,PB,HB,AA,round,Nation,year
421,1.0,vitaliy guimaraes,14.250,14.350,13.600,14.450,13.900,13.40,83.950,final,USA,2022
422,2.0,khoi young,13.550,15.342,12.550,15.244,13.750,13.10,83.536,final,USA,2022
423,3.0,asher hong,14.029,12.949,14.566,16.680,14.355,10.45,83.029,final,USA,2022
424,4.0,yul moldauer,13.400,13.789,14.116,13.400,15.543,11.40,81.648,final,USA,2022
425,5.0,colt walker,12.450,12.750,13.250,14.897,15.055,13.10,81.502,final,USA,2022
...,...,...,...,...,...,...,...,...,...,...,...,...
716,38.0,ian skirkey,0.000,14.972,0.000,0.000,0.000,0.00,14.972,final,USA,2023
717,39.0,ignacio yockers,0.000,14.942,0.000,0.000,0.000,0.00,14.942,final,USA,2023
718,40.0,brandon dang,0.000,14.466,0.000,0.000,0.000,0.00,14.466,final,USA,2023
719,41.0,vahe petrosyan,0.000,0.000,0.000,13.350,0.000,0.00,13.350,final,USA,2023
720,42.0,troy lipis,0.000,0.000,12.711,0.000,0.000,0.00,12.711,final,USA,2023

In [11]:
usa.sort_values(by='AA', ascending=False, inplace=True)

/var/folders/j_/555m2zps099832fjh_m8jjnc0000gn/T/ipykernel_89215/3476780909.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  usa.sort_values(by='AA', ascending=False, inplace=True)

In [12]:
usa = usa.drop(columns=['Rank', 'Rank', 'Nation', 'year'])

In [13]:
usa = usa.drop(columns=['round'])

In [14]:
df=usa.copy()

In [15]:
# df

In [16]:
# import pandas as pd
# from scipy.stats import percentileofscore

# # Athlete of interest
# athlete_name = 'vitaliy guimaraes'

# # Create a dictionary to store percentiles for each apparatus
# percentiles_dict = {}

# for apparatus in df.columns[1:-1]:  # Exclude 'Athlete' and 'AA' columns
#     scores = df[apparatus].values
#     athlete_score = df[df['Athlete'] == athlete_name][apparatus].values[0]
    
#     # Calculate percentile
#     percentile = percentileofscore(scores, athlete_score)
#     percentiles_dict[apparatus] = percentile

# # Display percentiles
# for apparatus, percentile in percentiles_dict.items():
#     print(f"{athlete_name} is in the {percentile:.2f} percentile for {apparatus}")

In [17]:
# import pandas as pd
# import seaborn as sns
# import matplotlib.pyplot as plt



# # Remove scores less than 5 for each apparatus
# for apparatus in df.columns[1:-1]:  # Exclude 'Athlete' and 'AA' columns
#     df = df[df[apparatus] >= 5]

# # Melt the DataFrame to long format for easier plotting
# df_long = pd.melt(df, id_vars=['Athlete'], var_name='Apparatus', value_name='Score')

# # Set the style of seaborn
# sns.set(style="whitegrid")

# # Iterate over each apparatus and create a separate scatter plot
# for apparatus in df.columns[1:-1]:  # Exclude 'Athlete' and 'AA' columns
#     plt.figure(figsize=(8, 6))
    


    
#     # Highlight 'vitaliy guimaraes' compared to everyone else
#     palette = ['grey' if athlete != 'vitaliy guimaraes' else 'red' for athlete in df_long['Athlete']]

#     # Create a scatter plot for the current apparatus
#     sns.scatterplot(x='Athlete', y='Score', hue='Athlete', data=df_long[df_long['Apparatus'] == apparatus], palette=palette, s=100)
    
#     plt.title(f'Scores on {apparatus} for Each Athlete')
#     plt.xlabel('Athlete')
#     plt.ylabel('Score')
#     plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', title='Athlete')
#     plt.xticks(rotation=45, ha='right')
#     plt.show()

In [18]:
# usa
# vitaliy guimaraes is in the 97.50 percentile for FX
# vitaliy guimaraes is in the 92.50 percentile for PH
# vitaliy guimaraes is in the 84.38 percentile for SR
# vitaliy guimaraes is in the 86.88 percentile for VT
# vitaliy guimaraes is in the 80.00 percentile for PB
# vitaliy guimaraes is in the 87.50 percentile for HB

# world
# vitaliy guimaraes is in the 92.09 percentile for FX
# vitaliy guimaraes is in the 94.04 percentile for PH
# vitaliy guimaraes is in the 84.47 percentile for SR
# vitaliy guimaraes is in the 87.59 percentile for VT
# vitaliy guimaraes is in the 74.62 percentile for PB
# vitaliy guimaraes is in the 80.51 percentile for HB

In [19]:
# import pandas as pd
# import seaborn as sns
# import matplotlib.pyplot as plt

# # Your DataFrame
# # df = ...

# # Athletes to highlight
# highlighted_athletes = ['asher hong', 'yul moldauer', 'fred richard', 
#                         'khoi young', 'vitaliy guimaraes']

# # Remove scores less than 5 for each apparatus
# for apparatus in df.columns[1:-1]:
#     df = df[df[apparatus] >= 5]

# # Melt the DataFrame to long format for easier plotting
# df_long = pd.melt(df, id_vars=['Athlete'], var_name='Apparatus', value_name='Score')

# # Set the style of seaborn
# sns.set(style="whitegrid")

# # Manually assign colors to the highlighted athletes
# highlighted_colors = {'asher hong': 'red', 'yul moldauer': 'blue', 
#                       'fred richard': 'green', 'khoi young': 'purple', 
#                       'vitaliy guimaraes': 'orange'}

# # Create a scatter plot for each apparatus
# for apparatus in df.columns[1:-1]:
#     plt.figure(figsize=(8, 6))

#     # Assign colors based on athlete
#     df_long['Color'] = df_long['Athlete'].map(lambda x: highlighted_colors.get(x, 'grey'))

#     # Create a scatter plot for the current apparatus
#     sns.scatterplot(x='Athlete', y='Score', hue='Color', data=df_long[df_long['Apparatus'] == apparatus], s=100)

#     plt.title(f'Scores on {apparatus} for Each Athlete')
#     plt.xlabel('Athlete')
#     plt.ylabel('Score')

#     # Manually create the legend
#     legend_labels = [plt.Line2D([0], [0], marker='o', color='w', markerfacecolor=color, markersize=10, label=athlete) for athlete, color in highlighted_colors.items()]
#     plt.legend(handles=legend_labels, bbox_to_anchor=(1.05, 1), loc='upper left', title='Athlete')
    
#     plt.xticks(rotation=45, ha='right')
#     plt.show()

In [20]:
# List of athletes to include
selected_athletes = ['asher hong', 'yul moldauer', 'fred richard', 
                     'khoi young', 'vitaliy guimaraes']

# Create a new DataFrame with only the selected athletes
selected_df = df[df['Athlete'].isin(selected_athletes)].reset_index(drop=True)

In [21]:
selected_df

             Athlete      FX      PH      SR      VT      PB      HB      AA
0       yul moldauer  14.400  13.957  14.114  14.250  15.121  13.500  85.342
1       fred richard  14.483  13.357  13.350  14.000  14.450  14.962  84.602
2  vitaliy guimaraes  14.250  14.350  13.600  14.450  13.900  13.400  83.950
3         khoi young  13.550  15.342  12.550  15.244  13.750  13.100  83.536
4         asher hong  14.029  12.949  14.566  16.680  14.355  10.450  83.029
5         asher hong  12.203  12.507  14.133  14.755  14.700  13.650  81.948
6       yul moldauer  13.400  13.789  14.116  13.400  15.543  11.400  81.648
7       fred richard  11.850  12.250  11.950  13.900  12.400  11.650  74.000
8         khoi young   0.000  11.200   0.000  14.802   0.000   0.000  26.002

In [22]:
df=selected_df.copy()

In [23]:
df

             Athlete      FX      PH      SR      VT      PB      HB      AA
0       yul moldauer  14.400  13.957  14.114  14.250  15.121  13.500  85.342
1       fred richard  14.483  13.357  13.350  14.000  14.450  14.962  84.602
2  vitaliy guimaraes  14.250  14.350  13.600  14.450  13.900  13.400  83.950
3         khoi young  13.550  15.342  12.550  15.244  13.750  13.100  83.536
4         asher hong  14.029  12.949  14.566  16.680  14.355  10.450  83.029
5         asher hong  12.203  12.507  14.133  14.755  14.700  13.650  81.948
6       yul moldauer  13.400  13.789  14.116  13.400  15.543  11.400  81.648
7       fred richard  11.850  12.250  11.950  13.900  12.400  11.650  74.000
8         khoi young   0.000  11.200   0.000  14.802   0.000   0.000  26.002

In [24]:
# import pandas as pd
# import seaborn as sns
# import matplotlib.pyplot as plt

# # Your DataFrame
# # df = ...

# # Athletes to highlight
# highlighted_athletes = ['asher hong', 'yul moldauer', 'fred richard', 
#                         'khoi young', 'vitaliy guimaraes']

# # Remove scores less than 5 for each apparatus
# for apparatus in df.columns[1:-1]:
#     df = df[df[apparatus] >= 5]

# # Melt the DataFrame to long format for easier plotting
# df_long = pd.melt(df, id_vars=['Athlete'], var_name='Apparatus', value_name='Score')

# # Set the style of seaborn
# sns.set(style="whitegrid")

# # Manually assign colors to the highlighted athletes
# highlighted_colors = {'asher hong': 'red', 'yul moldauer': 'blue', 
#                       'fred richard': 'green', 'khoi young': 'purple', 
#                       'vitaliy guimaraes': 'orange'}

# # Create a scatter plot for each apparatus
# for apparatus in df.columns[1:-1]:
#     plt.figure(figsize=(8, 6))

#     # Assign colors based on athlete
#     df_long['Color'] = df_long['Athlete'].map(lambda x: highlighted_colors.get(x, 'grey'))

#     # Create a scatter plot for the current apparatus
#     sns.scatterplot(x='Athlete', y='Score', hue='Color', data=df_long[df_long['Apparatus'] == apparatus], s=100)

#     plt.title(f'Scores on {apparatus} for Each Athlete')
#     plt.xlabel('Athlete')
#     plt.ylabel('Score')

#     # Manually create the legend
#     legend_labels = [plt.Line2D([0], [0], marker='o', color='w', markerfacecolor=color, markersize=10, label=athlete) for athlete, color in highlighted_colors.items()]
#     plt.legend(handles=legend_labels, bbox_to_anchor=(1.05, 1), loc='upper left', title='Athlete')
    
#     plt.xticks(rotation=45, ha='right')
#     plt.show()

In [25]:
# import pandas as pd
# import seaborn as sns
# import matplotlib.pyplot as plt
# import ipywidgets as widgets
# from ipywidgets import interact

# # Assuming df is your DataFrame

# # Function to filter scores based on a threshold
# def filter_scores(threshold):
#     filtered_df = df[df.iloc[:, 1:-1].ge(threshold).all(axis=1)]
#     return filtered_df

# # Create a slider widget for the score threshold
# threshold_slider = widgets.FloatSlider(
#     value=5,
#     min=0,
#     max=10,
#     step=0.1,
#     description='Score Threshold:'
# )

# # Use the interact decorator to update the plot based on the slider value
# @interact(threshold=threshold_slider)
# def plot_scores(threshold):
#     # Filter the DataFrame based on the threshold
#     filtered_df = filter_scores(threshold)
    
#     # Melt the DataFrame to long format for easier plotting
#     df_long = pd.melt(filtered_df, id_vars=['Athlete'], var_name='Apparatus', value_name='Score')
    
#     # Set the style of seaborn
#     sns.set(style="whitegrid")

#     # Iterate over each apparatus and create a separate scatter plot
#     for apparatus in filtered_df.columns[1:-1]:  # Exclude 'Athlete' and 'AA' columns
#         plt.figure(figsize=(8, 6))
        
#         # Highlight 'vitaliy guimaraes' compared to everyone else
#         palette = ['grey' if athlete != 'vitaliy guimaraes' else 'red' for athlete in df_long['Athlete']]

#         # Create a scatter plot for the current apparatus
#         sns.scatterplot(x='Athlete', y='Score', hue='Athlete', data=df_long[df_long['Apparatus'] == apparatus], palette=palette, s=100)
        
#         plt.title(f'Scores on {apparatus} for Each Athlete (Threshold: {threshold})')
#         plt.xlabel('Athlete')
#         plt.ylabel('Score')
#         plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', title='Athlete')
#         plt.xticks(rotation=45, ha='right')
#         plt.show()

In [26]:
# import pandas as pd
# import seaborn as sns
# import matplotlib.pyplot as plt
# import ipywidgets as widgets
# from ipywidgets import interact

# # Assuming df is your DataFrame

# # Remove scores less than 5 for each apparatus
# for apparatus in df.columns[1:-1]:
#     df = df[df[apparatus] >= 5]

# # Melt the DataFrame to long format for easier plotting
# df_long = pd.melt(df, id_vars=['Athlete'], var_name='Apparatus', value_name='Score')

# # Set the style of seaborn
# sns.set(style="whitegrid")

# # Manually assign colors to the highlighted athletes
# highlighted_colors = {'asher hong': 'red', 'yul moldauer': 'blue', 
#                       'fred richard': 'green', 'khoi young': 'purple', 
#                       'vitaliy guimaraes': 'orange'}

# # Create a dropdown widget for selecting the apparatus
# apparatus_dropdown = widgets.Dropdown(
#     options=df.columns[1:-1],
#     value=df.columns[1],
#     description='Apparatus:'
# )

# # Use the interact decorator to update the plot based on the dropdown value
# @interact(apparatus=apparatus_dropdown)
# def plot_scores(apparatus):
#     plt.figure(figsize=(8, 6))

#     # Assign colors based on athlete
#     df_long['Color'] = df_long['Athlete'].map(lambda x: highlighted_colors.get(x, 'grey'))

#     # Create a scatter plot for the selected apparatus
#     sns.scatterplot(x='Athlete', y='Score', hue='Color', data=df_long[df_long['Apparatus'] == apparatus], s=100)

#     plt.title(f'Scores on {apparatus} for Each Athlete')
#     plt.xlabel('Athlete')
#     plt.ylabel('Score')

#     # Manually create the legend
#     legend_labels = [plt.Line2D([0], [0], marker='o', color='w', markerfacecolor=color, markersize=10, label=athlete) for athlete, color in highlighted_colors.items()]
#     plt.legend(handles=legend_labels, bbox_to_anchor=(1.05, 1), loc='upper left', title='Athlete')
    
#     plt.xticks(rotation=45, ha='right')
#     plt.show()

In [27]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import ipywidgets as widgets
from ipywidgets import interact

# Assuming df is your DataFrame

# Remove scores less than 5 for each apparatus
for apparatus in df.columns[1:-1]:
    df = df[df[apparatus] >= 5]

# Melt the DataFrame to long format for easier plotting
df_long = pd.melt(df, id_vars=['Athlete'], var_name='Apparatus', value_name='Score')

# Set the style of seaborn
sns.set(style="whitegrid")

# Manually assign colors to the highlighted athletes
highlighted_colors = {'asher hong': 'red', 'yul moldauer': 'blue', 
                      'fred richard': 'green', 'khoi young': 'purple', 
                      'vitaliy guimaraes': 'orange'}

# Create a dropdown widget for selecting the apparatus
apparatus_dropdown = widgets.Dropdown(
    options=df.columns[1:-1],
    value=df.columns[1],
    description='Apparatus:'
)

# Update the plot_scores function to take widget values as arguments
@interact(apparatus=apparatus_dropdown)
def plot_scores(apparatus):
    plt.figure(figsize=(8, 6))

    # Assign colors based on athlete
    df_long['Color'] = df_long['Athlete'].map(lambda x: highlighted_colors.get(x, 'grey'))

    # Create a scatter plot for the selected apparatus
    sns.scatterplot(x='Athlete', y='Score', hue='Color', data=df_long[df_long['Apparatus'] == apparatus], s=100)

    plt.title(f'Scores on {apparatus} for Each Athlete')
    plt.xlabel('Athlete')
    plt.ylabel('Score')

    # Manually create the legend
    legend_labels = [plt.Line2D([0], [0], marker='o', color='w', markerfacecolor=color, markersize=10, label=athlete) for athlete, color in highlighted_colors.items()]
    plt.legend(handles=legend_labels, bbox_to_anchor=(1.05, 1), loc='upper left', title='Athlete')
    
    plt.xticks(rotation=45, ha='right')
    plt.show()

interactive(children=(Dropdown(description='Apparatus:', options=('FX', 'PH', 'SR', 'VT', 'PB', 'HB'), value='â€¦